### ISSUE TITLE
Invisible selected checkbox

### ISSUE THREAD

**Issue by matteoarrighi** [vinceliuice/vimix-gtk-themes#100]
Selected checkbox is invisible if its row is selected too.
Unselected
![checkbox_bug_unselected](https://user-images.githubusercontent.com/36959661/46103622-8e07c680-c1d1-11e8-9db2-3b7946061bc1.png)
Selected
![checkbox_bug_selected](https://user-images.githubusercontent.com/36959661/46103631-95c76b00-c1d1-11e8-8275-46b4ae06feeb.png)

**Comment by vinceliuice** [comment]
I'll fix this
