### ISSUE TITLE
Propably fix on light themes

### ISSUE THREAD

**Issue by gaou-piou** [vinceliuice/vimix-gtk-themes#101]
In gtk3 apps, like visual studio code, the menu background if #ffffff and it looks like a white row.
I think that the css in gtk-3.0/gtk.css must changed from this
```
menu,
.menu,
.context-menu {
  margin: 4px;
  padding: 2px 0px;
  box-shadow: none;
  background-color: #FFFFFF;
  border: none;
  border-radius: 0;
}
```
into this
```
menu,
.menu,
.context-menu {
  margin: 4px;
  padding: 2px 0px;
  box-shadow: none;
  background-color: #eeeeee;
  border: none;
  border-radius: 0;
}
```

**Comment by gaou-piou** [comment]
This is what we have now
![](https://image.ibb.co/jRuwie/current.png) 

and this is how it looks like with the fix 
![](https://image.ibb.co/m5frGz/fixed.png)

**Comment by vinceliuice** [comment]
So the menubar background color is full white, but this code will change all gtk3 app menu background color not the menubar background color,

**Comment by gaou-piou** [comment]
You are right.
So how we fix that?

**Comment by vinceliuice** [comment]
This makes me very confused, it should not be like this, because I already set menubar background color to #eeeeee, and I tried to install VS Code on my Ubuntu but it  is unable to start. anyway  is only my vimix light themes have this issue or other light theme like arc\materia have this issue too?

**Comment by vinceliuice** [comment]
Well thanks! I'll try find a way to fix this but not change the menu

**Comment by vinceliuice** [comment]
Fixed now!
