### ISSUE TITLE
Weird pathbar on Nautilus 3.30.1

### ISSUE THREAD

**Issue by jose-sanchezm** [vinceliuice/vimix-gtk-themes#102]
Hello, after the update to Nautilus 3.30.1 the pathbar looks out of place in many themes, including vimix.

![image](https://user-images.githubusercontent.com/18676221/46466628-23a3e700-c7cc-11e8-911b-04e4f271bce7.png)

Maybe there's a new class for the pathbar that needs to be taken into account.

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed now！
