### ISSUE TITLE
在xfce下，部分图标大小缩放异常

### ISSUE THREAD

**Issue by FateRover** [vinceliuice/vimix-gtk-themes#103]
系统信息
```
    ,g$$$$$$$$$$$$$$$P.       ---------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux unstable (sid) x86_64 
 ,$$P'              `$$$.     Kernel: 4.18.0-2-amd64 
',$$P       ,ggs.     `$$b:   Uptime: 1 hour, 21 mins 
`d$$'     ,$P"'   .    $$$    Packages: 1612 (dpkg) 
 $$P      d$'     ,    $$P    Shell: bash 4.4.23 
 $$:      $$.   -    ,d$$'    Resolution: 1920x1080 
 $$;      Y$b._   _,d$P'      DE: Xfce 
 Y$$.    `.`"Y$$$$P"'         WM: Xfwm4 
 `$$b      "-.__              WM Theme: Vimix-Light 
  `Y$$                        Theme: Arc [GTK2] 
   `Y$$.                      Icons: Numix [GTK2] 
     `$$b.                    Terminal: xterm 
       `Y$$b.                 CPU: Intel i5-4590 (4) @ 3.700GHz 
          `"Y$b._             GPU: NVIDIA GeForce GTX 750 Ti 
              `"""            Memory: 1895MiB / 7897MiB 

```
https://i.imgur.com/ujgNKNy.png
xfce的电池管理托盘图标，在面板高度为34的时候会提前放大，造成图标比其他的大一圈，这个好象是xfce、图标包、主题包多方面的问题  ：
https://github.com/numixproject/numix-icon-theme/issues/107
https://forum.xfce.org/viewtopic.php?id=11626
许多主题都存在这个问题，但是部分主题又额外做了补丁，比如 victory-gtk-theme-18.07　　即使同一个图标包，这个主题就不会出现问题。本主题能否也做适配。

**Comment by vinceliuice** [comment]
我去看看victory-gtk-theme的代码是怎么解决的好参考参考

**Comment by vinceliuice** [comment]
我加进去了，你下载最新的试试

**Comment by FateRover** [comment]
你是不是连pulseaudio的大小也调节了，目前电池图标正常，但是音量图标较其他偏小了。顺便，这俩图标节点是什么，我可以自己调整下缩放率。

**Comment by vinceliuice** [comment]
你去src/gtk-3.0/sass/_apps.scss这个文件里找到：
#xfce4-weather-plugin *,
#pulseaudio-button *,
#xfce4-power-manager-plugin *,
#xfce4-clipman-plugin * {
  -gtk-icon-transform: scale(.8);
}
然后把#pulseaudio-button *,这一行删掉，就不会对pulseaudio有影响了，需要修改的话可以改scale(.8);的值, .8就是缩放到0.8倍
