### ISSUE TITLE
input area border missing 

### ISSUE THREAD

**Issue by FateRover** [vinceliuice/vimix-gtk-themes#104]
OS:debian testing
DE:xfce4
some  border of input area were missing ,whisker menu and xfce4-verve,shown as gif
https://imgur.com/a/UmXspaF

**Comment by vinceliuice** [comment]
This is not a issue, I just unify all popover menu entry style to flat entry style, so all entry on menu will only have underlines and no borders any more

**Comment by FateRover** [comment]
ok,but the xfce-verve underline disappeared or it just have the same color underline with xfce panel?
