### ISSUE TITLE
Firefox has black bar at top

### ISSUE THREAD

**Issue by WingofaGriffin** [vinceliuice/vimix-gtk-themes#105]
![image](https://user-images.githubusercontent.com/19497824/46895904-7fafe080-ce48-11e8-87bb-faa29ba1f294.png)

This is most clear in full screen size, but firefox decides to have a black bar, preventing easy tab clicking by going to the top which is a little annoying.

I'm currently using Cinnamon as me DE.

**Comment by vinceliuice** [comment]
Fixed now
