### ISSUE TITLE
No colored titlebuttons on standard variants

### ISSUE THREAD

**Issue by matteoarrighi** [vinceliuice/vimix-gtk-themes#106]
I can't have colored titlebuttons on theme standard variants (-t standard) anymore. They are still present in doder, beryl and ruby variants.

**Comment by vinceliuice** [comment]
I changed the standard version titlebuttons to be more pure and high contrast，so I removed the color of it

**Comment by vinceliuice** [comment]
I changed the standard version titlebuttons to be more pure and high contrast，so I removed the color of it

**Comment by matteoarrighi** [comment]
Okay. Is there a way I can get them back? It would be great if colored titlebuttons in standard variants could be added as an option in `Install` script.

**Comment by vinceliuice** [comment]
Ok, I'll add this option in Install script.
