### ISSUE TITLE
Blue accent color on "true" dark grey background

### ISSUE THREAD

**Issue by Waryle** [vinceliuice/vimix-gtk-themes#108]
Hi!

First things first, I would like to thank you for this theme. I looked for the perfect gnome-shell theme for months before finally settling with this one, and I love it!

Now, I would like to customize it a bit. I like the dark-doder variant, but on some windows, I got a grey bar which does not fit with the slightly blue background of this variant.

So I tried to modify both the gnome-shell/sass/_color.scss and gtk-3.0/sass/_color.scss files, started parse_sass.sh, then installed the themes, but without success : the themes generated and installed are not modified in any way.

Can you enlighten me on what I have to modify to get a theme that fit those characteristics : 
- A "true grey" dark background, like on Vimix-Dark
- Blue accent color like on Vimix-Doder/Vimix-Doder-Dark
- Colored titlebar buttons

Thank you in advance for your help!

**Comment by vinceliuice** [comment]
Change "$base_color" on /src/gnome-shell/sass/_colors.scss, then run ./parse-sass.sh

**Comment by Waryle** [comment]
Didn't work for me, but I have found the solution : 

In src/gtk-3.0/sass, change the values of : 
- $bg_color
- $base_color 
- $lighter_bg_color
- $darker_bg_color
- $darker_fg_color
in the "Background colors" section, and : 
- $headerbar_bg_color
in the "Headerbar colors" section.

I write this down for me and anybody who might be interested.

Thanks for the help anyway, and thanks for the theme again!
