### ISSUE TITLE
Panel Issue

### ISSUE THREAD

**Issue by PFelipe23** [vinceliuice/vimix-gtk-themes#110]
I just installed the Vimix, and I can't change the panel's theme. How can I solve this issue? There's no  Vimix related stuff on "Desktop" section, only Cinnamon, Mint-X and Mint-Y themes.

![untitled](https://user-images.githubusercontent.com/19367722/48316756-ea327880-e5ce-11e8-83ab-c3a75ab1dbef.png)

Thanks in advance!

**Comment by vinceliuice** [comment]
Add Cinnamon themes now, you can try the new one again!

**Comment by PFelipe23** [comment]
Thanks a lot! One more question: Where I can find the triple dashed menu icon for the taskbar menu?
