### ISSUE TITLE
GDM支持？

### ISSUE THREAD

**Issue by Robosky** [vinceliuice/vimix-gtk-themes#111]
在src/gnome-shell/下可以看到有gnome-shell-theme.gresource.xml的，手动使用glib-compile-resources也可以成功安装gdm主题，为什么Install脚本没有--gdm选项支持呢？

**Comment by vinceliuice** [comment]
安装了gdm主题之后，会导致使用其他的gnome-shell主题时会优先使用系统默认的gnome-shell.css的代码，会导致一些外观问题，而且最新的ubuntu系统移除了glib-compile-resources，所以我就没提供gdm的选项了

**Comment by Robosky** [comment]
了解了，感谢回复

**Comment by vinceliuice** [comment]
不客气
