### ISSUE TITLE
请问演示图使用的是什么音乐播放器

### ISSUE THREAD

**Issue by JadeVane** [vinceliuice/vimix-gtk-themes#112]
很抱歉问这么一个完全不沾边的问题，不过确实很喜欢这个音乐播放器，能告知一下左下角这个是什么播放器吗？
![image](https://user-images.githubusercontent.com/34258753/49055550-ec354200-f232-11e8-8b1d-9798140ea363.png)

**Comment by vinceliuice** [comment]
Ubuntu自带的rhythmbox，这个播放器应该很长见的

**Comment by JadeVane** [comment]
感谢，因为用的不是ubuntu，还以为看到的是一个新的播放器呢。。。。

**Comment by vinceliuice** [comment]
哈哈，不客气，这个就是rhythmbox的一个插件把窗口改成了gnome统一的csd窗口了

**Comment by vinceliuice** [comment]
最小化到托盘的插件好像还没有哦
