### ISSUE TITLE
window border not working on mate

### ISSUE THREAD

**Issue by paperbenni** [vinceliuice/vimix-gtk-themes#113]
The Window border is not working on MATE. The controls work fine, even better than on the ubuntu version of gnome, but the window borders just get reset to something that looks like a placeholder. It's the same for all vimix variations. I really love the pretty-mac-but-not-too-apple style of the borders. I hope, you can get it working. 
Thanks in advance ;)

**Comment by vinceliuice** [comment]
Thanks for notice me that, I just forget this, But now I add it back, you can try again
