### ISSUE TITLE
[gnome shell]关于osd

### ISSUE THREAD

**Issue by jeffshee** [vinceliuice/vimix-gtk-themes#114]
stylish-gtk-theme也有相同的问题
https://github.com/vinceliuice/stylish-gtk-theme/issues/13

![vimix](https://user-images.githubusercontent.com/25530920/49484746-7d339b00-f87b-11e8-82d8-cdb121f34451.png)
如上图，音量/亮度调节osd里的barlevel似乎有点过细。而且调色也和主题有点不太搭配。正使用当前Vimix主题的最新版本。GNOME Shell 3.30.2 Fedora系统。

描述不当请原谅……^^

**Comment by vinceliuice** [comment]
我用的台式机无法调出这个osd窗口调节音量和亮度, 所以一直没注意这个问题, 我用我的笔记本试试修复这个问题吧

**Comment by vinceliuice** [comment]
你现在试一下最新版,我调整了一下

**Comment by jeffshee** [comment]
确认已修复，辛苦你了^^

**Comment by vinceliuice** [comment]
不客气
