### ISSUE TITLE
Animation not visible. 

### ISSUE THREAD

**Issue by paperbenni** [vinceliuice/vimix-gtk-themes#116]
I'm using gnome; arch btw ;) 
The dark-doder variant has some android-style animations when doing things like switching tabs in nautilus or gnome terminal. These seem to be missing on the standard variant. They're white on the other variants so I suspect they're actually there but white on a white background. Can you please make them gray/add them in the first place to the standard vimix theme?
I really love the look of them, but the dark theme causes some issues with some sites in firefox and some applications, so I'd like to use the light theme and have the animations. 
Thanks in advance ;)

**Comment by vinceliuice** [comment]
I checked, But the animation of tabs still there, I just shorten the time of the animation not removed it, Does it not works on your desktop?
