### ISSUE TITLE
Does it have a GDM theme?

### ISSUE THREAD

**Issue by tiotrom** [vinceliuice/vimix-gtk-themes#118]
I am suggesting this theme as the default one for Manjaro Gnome since I think is the best set of themes, but they guys there are saying that it is incomplete since it has to GDM theme.

**Comment by vinceliuice** [comment]
It do have a gdm theme, I just removed the install script

**Comment by tiotrom** [comment]
Ok thanks! I am letting them know maybe they could add your theme as the default Manjaro Gnome theme. How do you activate GDM for Vimix though?

**Comment by tiotrom** [comment]
Can you please follow up here on the discussion https://forum.manjaro.org/t/make-vimix-the-default-manjaro-gnome-theme/70784/9 - I honestly would love to see your theme being adopted by the Manjaro team. Maybe some Manjaro dev could also contribute to fix some issues with it

**Comment by vinceliuice** [comment]
OK, thanks! I'll add it back at future update

**Comment by Marijnrombouts** [comment]
Just wondering, was a gdm theme ever added to Vimix? That would be really cool, but I can't seem to find it.

**Comment by zepedros** [comment]
No news on a GDM theme?
