### ISSUE TITLE
terminal background color

### ISSUE THREAD

**Issue by frague59** [vinceliuice/vimix-gtk-themes#12]
Hi, 

First : thanks for this great theme !

I'm using terminix as terminal, but background color is a bit too clear, could it be set to a black or a dark gray ? terminal colors should be more readable...

Thanks !

**Comment by focmb** [comment]
you can set your terminal background color in the profile settings of terminix. The terminix backgroundcolor does not depends on the gtk theme

**Comment by frague59** [comment]
Got it, it work... Thanks !
