### ISSUE TITLE
GNOME 3.32下Shell主题问题

### ISSUE THREAD

**Issue by Robosky** [vinceliuice/vimix-gtk-themes#121]
在GNOME 3.32上，系统指示器的点击菜单内用户图标异常地放大了，如图
![截图](https://jw0t3a.dm.files.1drv.com/y4mpaGWt2mtdC2OCVJBHf0hTJF1jQfmhdU9dvL8XhZhwuCW45yYTOSkUlWrNUI0jFzpJplpvds2iquIVbMJapEuxauRC37-i0KBzbeme6MPH0TasDNgxZrVIHlzYqAL7MpvjEG4n2nsxWDR1Xiz_-Pcy0W_u4Qa3Kng981nokcAI_rjptCHHKbjABgiGD3g36YJhu1zM9PWRXeuK2giF-2olQ?width=329&height=409&cropmode=none)
有什么需要提交的信息以便更好地定位问题吗？

**Comment by vinceliuice** [comment]
好的, 马上就可以修复好

**Comment by vinceliuice** [comment]
修复了
