### ISSUE TITLE
Any plan to also port to QT

### ISSUE THREAD

**Issue by tiotrom** [vinceliuice/vimix-gtk-themes#122]
I love this theme and I use it as my main theme in Manjaro Gnome but there are many QT applications that struggle to match the theme. I am using QT5 Settings and Kvantum to try and match but is not a solution. If (maybe) there would be a QT Vimix theme as well it would blend most applications in Linux.

**Comment by jeffshee** [comment]
Please try this theme engine
https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle
Install `qt5-styleplugins` (the package name on your distro might differ) and add this to your environment variable
```
QT_QPA_PLATFORMTHEME="gtk2"
export QT_QPA_PLATFORMTHEME
```
I had achieved a good result by this method, here is how QT application looks like on my setup. (Using Vimix-dark-doder btw)
![Screenshot from 2019-04-20 21-09-22](https://user-images.githubusercontent.com/25530920/56457184-daa33100-63b1-11e9-9158-ca4aae7b7220.png)

Feel free to ask if you have any problem ;)

**Comment by tiotrom** [comment]
Thanks! I already have that setup but doesn't work well with some applications. For example here is how VirtualBox looks like
![2019-04-20_18-53](https://user-images.githubusercontent.com/34804533/56460112-bc333a80-639d-11e9-8e60-be07c73cf3f5.png)

**Comment by vinceliuice** [comment]
Vmix for kde will come!

**Comment by jeffshee** [comment]
Oppss that's true, I don't use VM so I didn't notice that...
As written on the ArchWiki, the theme engine way is indeed a "Hit or Miss"...
You can try this `QT_QPA_PLATFORMTHEME= virtualbox` to reset the variable before launching the apps which has problem, if it works then you might want to edit your .desktop file
1. Copy the .desktop file to your user applications directory (this should override the system one)
`cp /usr/share/applications/virtualbox.desktop ~/.local/share/applications/virtualbox.desktop`
2. Edit the .desktop file
`nano ~/.local/share/applications/virtualbox.desktop`
3. Find the Exec, modify it as below, save it finally
`Exec=env QT_QPA_PLATFORMTHEME= VirtualBox %U`

The apps should be at least usable for now. Please share if you can come out with a better idea ;)
![Screenshot from 2019-04-21 12-28-56](https://user-images.githubusercontent.com/25530920/56465062-4ed0e980-6431-11e9-98b2-8d199768c0de.png)

**Comment by tiotrom** [comment]
@jeffshee thank you! Yes it works like that. For now I don't have a better idea but I hope such things can be overcome when Vimix QT is available :) - I love this theme!

**Comment by vinceliuice** [comment]
Vimix-kde is here: https://github.com/vinceliuice/vimix-kde

**Comment by tiotrom** [comment]
I cannot see the kde theme in kvantum....I use Manjaro Gnome and installed from AUR

**Comment by vinceliuice** [comment]
@tiotrom you should install vimix-kde from here: https://github.com/vinceliuice/vimix-kde, because I just finished the first kde version yestoday, so you can not get it frome AUR

**Comment by Robosky** [comment]
> I cannot see the kde theme in kvantum....I use Manjaro Gnome and installed from AUR

I just upload it, you should install `kvantum-theme-vimix-git` from AUR to use Kvantum theme

**Comment by tiotrom** [comment]
Ok great! kvantum-theme-vimix-git works! I hope you'll also add the dark flavors :)

**Comment by vinceliuice** [comment]
@Robosky Thanks for upload vimix-kde to AUR! :)

**Comment by vinceliuice** [comment]
@tiotrom No problem! full light and full dark version is making now!

**Comment by tiotrom** [comment]
@Robosky Will you update the KDE theme with the dark versions?

**Comment by vinceliuice** [comment]
@tiotrom Dark version I'm still making
