### ISSUE TITLE
Use different font-colour for Nautilus' "Icon View Captions"

### ISSUE THREAD

**Issue by anupam207** [vinceliuice/vimix-gtk-themes#123]
Nautilus nowadays has an "Icon View Captions" feature:
![nautilas-prefs](https://user-images.githubusercontent.com/20688749/54873778-ff80a480-4e03-11e9-9c7b-4b509f9d7cca.png)

It can be used to show more info below the file/folder name (at most 3 more properties).

Vimix uses the same font colour and size for these captions and as well as the file/folder name:
![vimix-nautilus](https://user-images.githubusercontent.com/20688749/54873795-75850b80-4e04-11e9-8480-74c37d2cbf08.png)

This can be slightly confusing sometimes. It would be better if the captions use a different shade. For example, in case of Adwaita:
![adwaita-nautilus](https://user-images.githubusercontent.com/20688749/54873806-b715b680-4e04-11e9-9863-8d92843e242e.png)

Nautilus v3.26.4 (Ubuntu 18.04)
Vimix theme, dated 2019-03-12, downloaded from [gnome-look.org](https://www.gnome-look.org/p/1013698/)

**Comment by vinceliuice** [comment]
This is a good feature of nautilus, I'll update my theme to support it soon

**Comment by vinceliuice** [comment]
Fixed now!
