### ISSUE TITLE
thunar pathbar style

### ISSUE THREAD

**Issue by denikris** [vinceliuice/vimix-gtk-themes#124]
xubuntu 18.04
thunar 1.6.15

![image823](https://user-images.githubusercontent.com/16707606/55086067-5b844b00-50da-11e9-9ed6-57aa0cc67eb8.png)
please make the pathbar style look like nautilus file manager (like on your screenshot)

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Fixed now
