### ISSUE TITLE
select text color hard to read in dark background website

### ISSUE THREAD

**Issue by denikris** [vinceliuice/vimix-gtk-themes#125]
![image823](https://user-images.githubusercontent.com/16707606/55087810-4230ce00-50dd-11e9-926f-d88261b4cdf6.png)
please make select text with cursor is blue(or any color) by default in all variant, it's hard to see which text is selected when on chrome visiting site like youtube/9gag on "night mode" using vimix dark variant

**Comment by vinceliuice** [comment]
OK, I'll fixed this

**Comment by vinceliuice** [comment]
Fixed now!
