### ISSUE TITLE
thunar pathbar color in light variant

### ISSUE THREAD

**Issue by denikris** [vinceliuice/vimix-gtk-themes#127]
![image823](https://user-images.githubusercontent.com/16707606/55665143-24ddcb80-5864-11e9-9566-5b97643effbc.png)

can you also make smaller variant? i open dockbarx preferences and the "close" button on bottom unreachable because my 1366x768 laptop resolution

![Screenshot_2019-04-06_12-01-06](https://user-images.githubusercontent.com/16707606/55665120-d9c3b880-5863-11e9-82d0-9f668e6c5e6f.png)

**Comment by vinceliuice** [comment]
I am not good at making gtk2 themes, but I will try to do it, maybe you need to wait some days or weeks?

**Comment by vinceliuice** [comment]
Fixed
