### ISSUE TITLE
wrong colors with chrome >=73

### ISSUE THREAD

**Issue by aacebedo** [vinceliuice/vimix-gtk-themes#128]
I am using Chrome 73 and I have notice there is an issue with colors using the GTK+ mode.
On the suggestions or on the download bar, the colors have changed and text are not readable anymore.

![image](https://user-images.githubusercontent.com/1217680/55966171-30702e80-5c78-11e9-9d02-db114e1016aa.png)

This issue was not there with chrome 72.
I am using vimix release from 2019-01-04 with variant vimix-dark-laptop-doder

**Comment by vinceliuice** [comment]
Fixed now

**Comment by aacebedo** [comment]
Thanks :+1:

**Comment by Sherlock-Holo** [comment]
@vinceliuice 
I use arch linux and install archcn package vimix-gtk-themes-git, version r345.92d0564-1
and the chrome search box is dark 
![image](https://user-images.githubusercontent.com/10096425/65376607-8c81b900-dcd4-11e9-8e46-05e8286334f4.png)
the gnome menu 
![image](https://user-images.githubusercontent.com/10096425/65376612-973c4e00-dcd4-11e9-9df9-ee9ae6bbc428.png) is soo light

**Comment by Sherlock-Holo** [comment]
and my theme setting is 
![image](https://user-images.githubusercontent.com/10096425/65376659-17fb4a00-dcd5-11e9-9c19-b347e7b10a08.png)

**Comment by vinceliuice** [comment]
I'll check this

**Comment by aacebedo** [comment]
Unfortunately problem is back.
Tested on manjaro vimix r348.eb398ee-1 installed an  chrome 78.
Autocomplete suggestions are black on black.
