### ISSUE TITLE
color inconsistency in dark theme for right click menu

### ISSUE THREAD

**Issue by aacebedo** [vinceliuice/vimix-gtk-themes#129]
I have upgraded vimix theme withe the latest master version.
It seems there is a small regression on right-click menus for vimix-dark variants.
In some applications such as Visual Studio Code or Chrome, the colors of the menu does not match the rest of the interface (background are light for example)

Can you confirm that statement ?

**Comment by vinceliuice** [comment]
VS code and Atom are Chomium based apps, So if I fixed #128 These apps will also be affected

**Comment by vinceliuice** [comment]
I‘m looking for a better solution

**Comment by aacebedo** [comment]
Thanks !
