### ISSUE TITLE
Vertical bars in window decoration

### ISSUE THREAD

**Issue by elvisd** [vinceliuice/vimix-gtk-themes#13]
In gtk3 applications there are unappealing vertical bars (see scrennshot, terminix left+right side; nautilus right side)
![screenshot from 2017-03-01 08-55-43](https://cloud.githubusercontent.com/assets/307127/23450885/b275f958-fe5d-11e6-8dfe-00b4c8613c68.png)

**Comment by vinceliuice** [comment]
Removed now！
