### ISSUE TITLE
Glitches found on several gnome extensions

### ISSUE THREAD

**Issue by jeffshee** [vinceliuice/vimix-gtk-themes#132]
OS: Fedora 29, GNOME Shell 3.30.2, Vimix latest version
Glitches found on several gnome extensions
1. [Extensions] https://extensions.gnome.org/extension/1036/extensions/
The lower part of the list turn transparent
![extensions](https://user-images.githubusercontent.com/25530920/56456822-bbee6b80-63ac-11e9-8da7-ac937eb3d4a2.png)

2. [Appfolders Management extension] https://extensions.gnome.org/extension/1217/appfolders-manager/
The color of the appfolders aren't correct, was semi-transparent on the earlier version.
![apps_menu](https://user-images.githubusercontent.com/25530920/56456824-c446a680-63ac-11e9-81d3-0e63b1fcb4bd.png)

上述Gnome插件的显示有些问题，有劳大大过目一下，谢谢^^

**Comment by vinceliuice** [comment]
好的，我看看

**Comment by vinceliuice** [comment]
第二个问题修复了，第一个问题的话我发现是插件的问题，这个插件没有提供滚动栏，如果屏幕不够大的话下面的就看不到
