### ISSUE TITLE
Ibus IME trun transparent

### ISSUE THREAD

**Issue by jeffshee** [vinceliuice/vimix-gtk-themes#133]
OS: Fedora 29, GNOME Shell 3.30.2, Vimix latest version
Ibus IME trun transparent, having difficulties to input, only Ibus Intelligent Pinyin was tested, might affect other IME as well.
![ibus](https://user-images.githubusercontent.com/25530920/56456923-3c619c00-63ae-11e9-82ea-d1ce76f2ab35.png)

Ibus输入法的视窗变透明，字都看不见了。麻烦大大修改一下><|||
测试时使用的是Ibus自带的智能拼音Intelligent Pinyin

**Comment by vinceliuice** [comment]
好的，这个好修复

**Comment by vinceliuice** [comment]
这个问题修复了
