### ISSUE TITLE
High res wallpaper?

### ISSUE THREAD

**Issue by Micro-Biology** [vinceliuice/vimix-gtk-themes#134]
Hello, 

I know wallpapers are available here:

https://github.com/vinceliuice/vimix-gtk-themes/tree/images

Are they available at higher resolutions anywhere?

**Comment by vinceliuice** [comment]
I'll upload higher resolution wallpapers at future updates

**Comment by vinceliuice** [comment]
Now it' ok: https://github.com/vinceliuice/vimix-gtk-themes/tree/images/wallpapers
