### ISSUE TITLE
The color of the "Cancel" in the confirmation box of chrome is too light

### ISSUE THREAD

**Issue by inhzus** [vinceliuice/vimix-gtk-themes#135]
### Version:

I have updated the latest version of vimix.

Vimix: vimix-dark-laptop

OS: Ubuntu 18.04 LTS

Browser: Chrome 73

### Problem:

I'm using vimix-dark-laptop theme, and I set my chrome to use GTK+ theme (Just the same as the theme of my desktop environment).

However, I find that the **color of the "Cancel" in the confirmation box is so light** that I cannot recognize. 

![image](https://user-images.githubusercontent.com/22855893/56549342-1ce89000-65b5-11e9-830e-3ea7e8762157.png)

So I really hope that you can change the color of "cancel" in the confirmation box if it is possible.

Thanks!

以下是中文翻译(我的英文不是很好, 见谅):

我正在使用 vimix-dark-laptop 主题, 在 chrome 设置中我使用了 GTK+ 主题, 也就是使用了桌面环境的默认设置.

但是我发现在确认框中 "Cancel" 的颜色太浅, 或者说与取消按钮的颜色非常相近, 导致看不大清, 尽管取消框中的字无关紧要, 但看起来确实很不舒服.

如果可能的话, 非常希望作者能够解决我的这一问题.

谢谢!

**Comment by inhzus** [comment]
I find that the color of the input of the search bar is difficult to recognize too.

刚刚发现搜索框中输入的颜色与背景对比也很浅.

![image](https://user-images.githubusercontent.com/22855893/56552079-b2d3e900-65bc-11e9-818b-75f9d651bc8e.png)

**Comment by vinceliuice** [comment]
现在应该修复了

**Comment by inhzus** [comment]
@vinceliuice 谢谢! 麻烦了.

**Comment by vinceliuice** [comment]
没事,不客气
