### ISSUE TITLE
The menu bar of VS Code is hard to recognize

### ISSUE THREAD

**Issue by inhzus** [vinceliuice/vimix-gtk-themes#136]
I have updated the latest version of vimix gtk themes: vimix-dark-laptop.

The example is as follows.

![image](https://user-images.githubusercontent.com/22855893/56581071-b2604000-6606-11e9-85f8-098f73c7e41c.png)

我觉得是不是中午的修改导致 VS Code 菜单栏的颜色一起发生变化了...

**Comment by vinceliuice** [comment]
字体都看不清吗

**Comment by inhzus** [comment]
以前是应该显示 File, Edit ... 嘛，现在背景颜色和菜单栏中字的颜色几乎完全一样了… 现在点菜单栏只能靠记忆了…

**Comment by vinceliuice** [comment]
我更新了一下,改了菜单背景 你再试试

**Comment by inhzus** [comment]
感谢! 效果正常了.

**Comment by vinceliuice** [comment]
不客气
