### ISSUE TITLE
Dock running indicators missing

### ISSUE THREAD

**Issue by jose-sanchezm** [vinceliuice/vimix-gtk-themes#137]
Hello, in the latest version as of 25th of April, the indicators for running applications are missing from the dock in gnome shell.

This is a screenshot with vimix-dark-laptop-dooder

![image](https://user-images.githubusercontent.com/18676221/56732687-6de7b800-675e-11e9-9f54-31a1c88eb154.png)

The same running applications using the default adwaita theme

![image](https://user-images.githubusercontent.com/18676221/56732738-92dc2b00-675e-11e9-927d-75ff158ed859.png)

Not very visible but at least they are there

**Comment by vinceliuice** [comment]
Can you tell me your desktop and gnome-shell version, because I don't have issues on my gnome 3.32

**Comment by jose-sanchezm** [comment]
gnome-shell  1:3.32.1-1 in Arch Linux

**Comment by vinceliuice** [comment]
![2019-04-25 20-08-23 的屏幕截图](https://user-images.githubusercontent.com/7604295/56734627-f3d32580-6795-11e9-9dc7-b1f68c7f8934.png)
That's my desktop, is only vimix theme have issues on your dash to dock?

**Comment by jose-sanchezm** [comment]
I see you are using transparency so I guess you don't have this option marked

![image](https://user-images.githubusercontent.com/18676221/56735113-de91d300-6764-11e9-86be-7b031e761cd3.png)

It only happens with this option. In fact, if I enable and disable it then it works as expected and the dots appear regardless of the setting. However, if I log out and log in again with the option marked, the dots dissapear again.

Also, I'm in Gnome Shell 3.32.1 while you are in 3.32.0 so there might be a regression with this point release.

**Comment by vinceliuice** [comment]
Now, it's fixed!

**Comment by jose-sanchezm** [comment]
Thanks!

**Comment by vinceliuice** [comment]
You are welcome!
