### ISSUE TITLE
Gnome terminal mistexture

### ISSUE THREAD

**Issue by Micro-Biology** [vinceliuice/vimix-gtk-themes#139]
Hello, seems to be an issue with the terminal not rendering part of the top icons correctly. it tries to use the icon for the terminal instead of what it should be.

![Screenshot from 2019-04-27 20-24-32](https://user-images.githubusercontent.com/34277641/56854226-05016b00-692b-11e9-8baa-39077795d27f.png)

**Comment by vinceliuice** [comment]
That nust be a issue about gtk theme, but you are using ubuntu default theme : "Ambiance"
