### ISSUE TITLE
Override Chrome Theme

### ISSUE THREAD

**Issue by denzelwamburu** [vinceliuice/vimix-gtk-themes#14]
Great Work on the theme.

Can you improve it to override chrome theme. Am using the `VimixDark-Doder`, but still the chrome light theme remains.
Can it be like the example below. - This is from `Adapta-Nokto`
![screenshot from 2017-03-02 14-09-58](https://cloud.githubusercontent.com/assets/6532631/23504760/edd84c7c-ff51-11e6-8d89-14e91f372cd8.png)

**Comment by johnpena** [comment]
You can make chrome use your GTK theme by going into [your chrome settings](chrome://settings/) and clicking the "use GTK+" button under the Appearance section.  

![screenshot from 2018-05-12 16-12-42](https://user-images.githubusercontent.com/43687/39962300-5f9a72c2-55ff-11e8-99b5-df834a4f51f8.png)
