### ISSUE TITLE
最新一个commit导致chrome部分控件呈现黑底黑字

### ISSUE THREAD

**Issue by zq1997** [vinceliuice/vimix-gtk-themes#146]
commit `92d0564f523e3bfa9d4a7e803431e5c1e851731e`更新了chrome有关，导致部分情况下黑底黑字。

如ctrl+F时的搜索框
![image](https://user-images.githubusercontent.com/17429111/65419559-7dfce400-de31-11e9-82d1-4a3da896ece0.png)
以及自动填充提示等控件。

**Comment by vinceliuice** [comment]
现在修复了
