### ISSUE TITLE
Nemo (as root) not theming

### ISSUE THREAD

**Issue by dm2912** [vinceliuice/vimix-gtk-themes#149]
Not a massive issue but Nemo when in root is not theming. 

![Screenshot_2019-12-31_03-00-56](https://user-images.githubusercontent.com/25871666/71608540-e4547980-2b79-11ea-98d4-76bf9c5af8ff.png)

LinuxMint 19.3 • XFCE 4.14

**Comment by vinceliuice** [comment]
If you want root user can also use this theme then you need to install this theme with sudo, you can run this: `sudo ./install.sh`

**Comment by dm2912** [comment]
aha... magic :D
