### ISSUE TITLE
Icon and Wallpaper

### ISSUE THREAD

**Issue by dbasinge** [vinceliuice/vimix-gtk-themes#15]
Not and issue, but what what are icons are in shown in the screenshots and where can I find those wallpapers.

**Comment by cwchien** [comment]
Icon Theme is Paper
You can find it here [https://snwh.org/paper](https://snwh.org/paper)

**Comment by vinceliuice** [comment]
Wallpapers that vimix used are here: https://github.com/vinceliuice/vimix-gtk-themes/tree/images

**Comment by juninho** [comment]
@vinceliuice, FYI, the link in page https://github.com/vinceliuice/vimix-gtk-themes ("You can download here:") is broken. It's point to /image, but should be pointing to /images.

**Comment by vinceliuice** [comment]
Thanks！ I fixed
