### ISSUE TITLE
当窗口失去焦点后最大化按钮没有变灰

### ISSUE THREAD

**Issue by zq1997** [vinceliuice/vimix-gtk-themes#150]
Linux Mint 19.3

当窗口失去焦点后，三个窗口按钮变色如图
![image](https://user-images.githubusercontent.com/17429111/71798333-9f09dd80-308c-11ea-8153-3df2274a1b53.png)

![image](https://user-images.githubusercontent.com/17429111/71798328-9a452980-308c-11ea-847f-2fc824fc380a.png)

其他两个都灰了，只有最大化还绿着，这个是bug还是feature😲?

追加：
好像和窗口已经最大化有关，只有已经最大化后才有上述现象。

**Comment by vinceliuice** [comment]
没事, 我现在修复了

**Comment by vinceliuice** [comment]
你下载最新的试试

**Comment by zq1997** [comment]
最新版好嘞，谢谢了

**Comment by vinceliuice** [comment]
不客气
