### ISSUE TITLE
gnome-shell app menu  is transprent

### ISSUE THREAD

**Issue by handbye** [vinceliuice/vimix-gtk-themes#153]
![image](https://user-images.githubusercontent.com/26617058/74083398-9c8d1000-4a9e-11ea-9178-fedf4420963c.png)

This is not conducive to viewing， can set a background?

**Comment by vinceliuice** [comment]
你下载最新的试一下，现在应该修复了。

**Comment by handbye** [comment]
已修复，感谢

**Comment by vinceliuice** [comment]
不客气！
