### ISSUE TITLE
Button issues on my xfce desktop

### ISSUE THREAD

**Issue by bobby285271** [vinceliuice/vimix-gtk-themes#154]
![截图_2020-03-08_23-31-57](https://user-images.githubusercontent.com/20080233/76165938-ecdab900-6195-11ea-8ec7-e6925f356aba.png)
Hi. I am using archlinux and I installed `vimix-gtk-themes-git` from the archlinuxcn repo, here is the [pkgbuild](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/vimix-gtk-themes-git/PKGBUILD) file. I set the theme in xfce settings manager, both the xfwm section and the theme section. Then I tested the theme on some gtk based apps and I found the buttons are not displayed in the same layout.

For example the buttons at the bottom of the lightdm gtk greeter settings window, acted different from the one at the bottom of the xfce4-terminal settings window.

The issue can be found on all vimix-* themes but doesn't appear on other themes like arc and materia.

I don't know whether the issue shares a same bug or feature with #152 so I create a new issue here.

**Comment by vinceliuice** [comment]
Fixed!
