### ISSUE TITLE
Latest commit (1515ae2 10 days ago) of vimix-gtk-themes still error on gnome 3.36

### ISSUE THREAD

**Issue by suiahae** [vinceliuice/vimix-gtk-themes#155]
![image](https://user-images.githubusercontent.com/45323123/77217390-106e0e00-6b5d-11ea-9d79-45cf479c828f.png)
 Just like this

**Comment by vinceliuice** [comment]
好的，我会修复这个问题的

**Comment by suiahae** [comment]
@vinceliuice 发现通知栏消息也有些问题
![image](https://user-images.githubusercontent.com/45323123/77628500-1875e580-6f83-11ea-867b-aac084e33177.png)
