### ISSUE TITLE
Xed close confirmation dialog - suggested button unreadable

### ISSUE THREAD

**Issue by Gotolei** [vinceliuice/vimix-gtk-themes#158]
Green text on green background.
`.dialog-action-area button.suggested-action`
https://i.imgur.com/0JHNj3m.png
(r359.1515ae2-1 AUR)

The backgrounds are new since 2020-02-24:
https://i.imgur.com/shPyVdy.png

**Comment by samuelcecilio** [comment]
![Peek 2020-10-14 14-09](https://user-images.githubusercontent.com/30150045/96022439-3fb0d900-0e27-11eb-9fb9-e3190b8dc5c3.gif)

**Comment by vinceliuice** [comment]
Fixed
