### ISSUE TITLE
xmllint on Xubuntu 16.04

### ISSUE THREAD

**Issue by mhammerc** [vinceliuice/vimix-gtk-themes#16]
Hello ! When running the installer script, I had an error.

    XMLLINT not set and xmllint not found in path; skipping xml preprocessing.

To fix it I had to install libxml2-utils

    sudo apt install libxml2-utils

Maybe we should add it to the README.

Have fun

**Comment by vinceliuice** [comment]
Thanks man

**Comment by mhammerc** [comment]
You're welcome :D
