### ISSUE TITLE
Consider grey window widgets for Dark Variants

### ISSUE THREAD

**Issue by stevenjaycohen** [vinceliuice/vimix-gtk-themes#162]
Have you considered grey circles in place of the yellow/green/red circles for the dark variants?

I do like that you are using the color of the circles to indicate focus, but I am remembering how Apple uses the circles when you choose graphite. And, I imagine you could do something similar.

**Comment by vinceliuice** [comment]
./install.sh -o to install grey titlebuttons in standard variants

**Comment by stevenjaycohen** [comment]
Fantastic!
