### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by filippogambarota** [vinceliuice/vimix-gtk-themes#164]
I'm on Ubuntu 18.04 and i've cloned the repository, opened the terminal on location and typed `./install.sh`. However, the terminal give me several times this message (this is an example but for every line of installation is the same) `cp: cannot stat 'Setup/vimix-gtk-themes/src/unity': No such file or directory`.
Inside the `.themes` folder there are all folder themes but inside the tweak tool are not availble. How can i do?

**Comment by hamhaingaurav** [comment]
Same problem is also occurred with me.

**Comment by vinceliuice** [comment]
Fixed
