### ISSUE TITLE
[gnome-shell] Dark variant black text

### ISSUE THREAD

**Issue by pkoutsovasilis** [vinceliuice/vimix-gtk-themes#165]
![Screenshot from 2020-04-13 03-46-44](https://user-images.githubusercontent.com/12166023/79083965-fa0d3980-7d39-11ea-8673-49e3c7d07c38.png)
![Screenshot from 2020-04-13 03-46-53](https://user-images.githubusercontent.com/12166023/79083967-fb3e6680-7d39-11ea-89ba-c4793c906906.png)

Firstly thanx for this amazing theme! IMHO the black text, as shown above in the pictures, should be somewhat whiter (gray maybe!?). This happens for the dark variant of vimix-gtk on gnome-shell 3.36.1.

**Comment by stevenjaycohen** [comment]
Confirmed. I was about to report this.
Ubuntu 20.04 beta ships with a version that's affected.

**Comment by pawel-szopinski** [comment]
Pop OS 19.10 is affected even more (calendar days barely visible)

![Untitled](https://user-images.githubusercontent.com/25465830/79670778-c14fe300-81c5-11ea-87b7-8cdba7261662.png)

**Comment by vinceliuice** [comment]
Fixed
