### ISSUE TITLE
[dark variant] Two issues in chrome

### ISSUE THREAD

**Issue by pawel-szopinski** [vinceliuice/vimix-gtk-themes#167]
Hello,

First of all, thanks for this amazing theme. It's been my daily driver for a couple of months now and nearly everything is perfect. However, I found two issues (apart from the calendar ones mentioned in the other thread). They relate to Chrome (GTK+ theme):
1. address bar is the same as the whole panel when out of focus. It's not a huge problem, but making it a tad brighter than the rest would definitely help.
2. password saving dialog is a bit off

![Untitled](https://user-images.githubusercontent.com/25465830/79671700-d1b78c00-81cc-11ea-81d6-3bb56e5bd836.png)

**Comment by ManjinderSingh131** [comment]
Autocomplete is also dark text on black background

**Comment by willww64** [comment]
Thank you for your great theme! I found the similar problem on chromium. The tab bar was dark but the rest of the chromium layout is light. The original material-dark theme doesn't have this problem.

**Comment by spont4e** [comment]
I have a problem with Update manager on my Linux Mint 20.1 looks like a light theme, but I'm with **Numix Dark Beryl Laptop** theme
![image](https://user-images.githubusercontent.com/10523455/104555591-ce134180-5646-11eb-9bf6-83e0a7fb2782.png)

**Comment by vinceliuice** [comment]
@spont4e install this theme with sudo

**Comment by spont4e** [comment]
> @spont4e install this theme with sudo

Thanks, work perfect!
