### ISSUE TITLE
Always use white for current directory in header of nautilus.

### ISSUE THREAD

**Issue by lixiaoyan** [vinceliuice/vimix-gtk-themes#17]
When using 'dark-ruby' or 'dark-doder' variant, it's a bit difficult to read the current directory name in header of nautilus.

**Comment by vinceliuice** [comment]
Can you tell me your system and you desktop you are using now!

**Comment by Paviluf** [comment]
I agree 
![screenshot from 2017-04-29 13-49-34](https://cloud.githubusercontent.com/assets/17159065/25555293/c4a68f94-2ce2-11e7-8c29-dd8bfc661be6.png)
