### ISSUE TITLE
Theme messes with the top bar

### ISSUE THREAD

**Issue by thehyperpineapple** [vinceliuice/vimix-gtk-themes#170]
I recently upgraded to Ubuntu 20.04 and i noticed that my top bar overlapped my window tabs causing me to often misclick the top bar icons when i wanted to close my window. When i changed my theme to the ones built in ubuntu the problem was solved. So please look into this issue so that i can go back to using vimix asap.

**Comment by avil25** [comment]
I am also facing same problem 
![Screenshot from 2020-04-27 11-20-10](https://user-images.githubusercontent.com/40562410/80357678-f381d480-8898-11ea-9181-4c14d4c691ce.png)

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
Fixed！
