### ISSUE TITLE
Minor problem in Files

### ISSUE THREAD

**Issue by Jing-Linux** [vinceliuice/vimix-gtk-themes#171]
When I use vimix-dark-beryl theme ,I right click the folder in Nemo, then 'Properties' section.There should be four sections : 'Basic' ; 'Permission' ; 'Share' ; and ‘Emblem’,but I can't see either one of them.

**Comment by vinceliuice** [comment]
Could you give me a screenshot?

**Comment by Jing-Linux** [comment]
![Screenshot from 2020-04-30 09-45-25](https://user-images.githubusercontent.com/64244331/80663753-72f4eb00-8ac7-11ea-82f6-e2dec7bd7023.png)

**Comment by vinceliuice** [comment]
What's your nemo version? I don't have this issue on my nemo 4.4.2

**Comment by Jing-Linux** [comment]
![Selection_003](https://user-images.githubusercontent.com/64244331/80786268-a44be480-8bb5-11ea-9e0d-2cef4173f0ff.png)

**Comment by vinceliuice** [comment]
![2020-05-01 16-42-05 的屏幕截图](https://user-images.githubusercontent.com/7604295/80794830-6fe42280-8bcd-11ea-8be6-ea203490c364.png)

**Comment by Jing-Linux** [comment]
I'm using cinnamon

**Comment by Jing-Linux** [comment]
所以请你改正一下英文语言的界面吧

**Comment by vinceliuice** [comment]
![Screenshot from 2020-05-13 23-17-51](https://user-images.githubusercontent.com/7604295/81832118-b728c680-9570-11ea-80b8-6dcaa962e467.jpeg)

**Comment by Jing-Linux** [comment]
a
