### ISSUE TITLE
Install script doesn’t handle -d and -n flags properly

### ISSUE THREAD

**Issue by rouhannb** [vinceliuice/vimix-gtk-themes#175]
For whatever reason, a recent commit changed what are now lines 238 and 242 from `shift 2` to `shift`. This causes a bug where using the `-d` or `-n` flag will cause the script to try to interpret the next parameter (which should be the value of those flags) as a flag itself, and then the script fails.

Reverting lines 238 and 242 back to `shift 2` should solve the issue.

**Comment by vinceliuice** [comment]
Thanks, I fixed this!
