### ISSUE TITLE
Amethyst dark theme has a fully transparent notifications pane background

### ISSUE THREAD

**Issue by flotwig** [vinceliuice/vimix-gtk-themes#177]
![image](https://user-images.githubusercontent.com/1151760/81611780-ab3ed800-93a9-11ea-8c23-9a7c78995e3c.png)

cc @wiccan2, have you had this issue?

**Comment by flotwig** [comment]
Oh, it's actually *any* dropdown from the topbar that looks like this.

Still, the purple is so pretty, I can't switch away...

**Comment by wiccan2** [comment]
@flotwig I haven't seen this no, but I'm not using Gnome so I guess I wouldn't ever see it.

I would guess the issue is in the Gnome Shell theme. I can get a VM set up with Gnome and take a look to see what I can do.

**Comment by wiccan2** [comment]
@flotwig I've found the bug and put a fix in. Once the PR is approved you should get a background on the dropdowns.

Seems I missed a conditional in the install script when I added the purple.

**Comment by flotwig** [comment]
@wiccan2 thanks!
