### ISSUE TITLE
ubuntu 20.04 本主题对窗体按钮不生效

### ISSUE THREAD

**Issue by zq1997** [vinceliuice/vimix-gtk-themes#180]
系统： ubuntu 20.04
窗口上的 最小化-最大化-关闭按钮 还是原生样式，没有便从红黄蓝三色小圆点，我自install 时候指定了-f参数也没有用
![image](https://user-images.githubusercontent.com/17429111/84750746-46048500-afee-11ea-8696-6d9be36abbff.png)

**Comment by vinceliuice** [comment]
直接安装不要加 -f, 加了 -f就会安装原生样式的版本

**Comment by zq1997** [comment]
害，我给弄反了，抱歉，直觉总觉得圆点那个才是扁平化的。
另外报个小bug (laptop还是生成了)
![image](https://user-images.githubusercontent.com/17429111/84756755-cbd7fe80-aff5-11ea-9ea0-730dae7ad9f5.png)

**Comment by vinceliuice** [comment]
好的，我会修复的
