### ISSUE TITLE
Color variants installation problem

### ISSUE THREAD

**Issue by fblais** [vinceliuice/vimix-gtk-themes#181]
Hi.
Running Limux Mint 20 here. (based on Ubuntu 20.04)
I clone the repo and compiled it to get flat title-buttons and the beryl color, but it only installs the doder color.
./install.sh -t beryl -f
Maybe the script is no longer compatible with Ubuntu 20.04?
Thanks!

**Comment by AdrianTwo** [comment]
Same problem with Linux Mint 19.3

**Comment by fblais** [comment]
Thanks!
I even tried the -o command line switch alone and only the doder color was installed.

**Comment by vinceliuice** [comment]
I fixed this now!

**Comment by yochananmarqos** [comment]
It was working on Manjaro GNOME, but now that you "fixed" it, something is wrong. I'm running `./install.sh -a -d "$pkgdir/usr/share/themes"` in my [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/blob/master/vimix-gtk-themes-git/PKGBUILD) and it's maxing out one of my CPU cores doing something. There's no terminal output, so I have no idea what it's trying to do.
