### ISSUE TITLE
Eclipse "Toggle buttons" not changing state

### ISSUE THREAD

**Issue by fgl82** [vinceliuice/vimix-gtk-themes#186]
In the Eclipse IDE, buttons/toggle switches such as "pin console", which should show if they are depressed or not, look unchanged even if they are actually pressed.
Linux Mint 20
Cinnamon

**Comment by kris7t** [comment]
I think I have found the cause of this problem and created a workaround in #191. However, it is possible that the error into the complied CSS was introduced by a Sass bug.
