### ISSUE TITLE
Memory Leak in xfce4 Appmenu Plugin

### ISSUE THREAD

**Issue by hamhaingaurav** [vinceliuice/vimix-gtk-themes#188]
When xfce4 4.14 update came, after that update whenever i apply this theme in my system, xfce4 appmenu plugin starts leaking the memory, extended cpu usage in app menu plugin and ram usage reaches unlimited. Please find out why only this theme is causing the error, I am currently using Flat Remix Gtk theme on my system without any extended cpu usage or ram leak of app menu plugin.
![Screenshot_2020-09-07_09-51-36](https://user-images.githubusercontent.com/34805677/92348140-bf90a880-f0ef-11ea-863f-bafa559ea1e1.png)
![Screenshot_2020-09-07_09-53-07](https://user-images.githubusercontent.com/34805677/92348190-f666be80-f0ef-11ea-98ab-35689fea3be3.png)

**Comment by vinceliuice** [comment]
Fixed !
