### ISSUE TITLE
Invisible icons and checkbox in Linux Mint 20

### ISSUE THREAD

**Issue by samuelcecilio** [vinceliuice/vimix-gtk-themes#189]
![Peek 28-09-2020 14-42](https://user-images.githubusercontent.com/30150045/94467315-235f3c00-0199-11eb-9fe9-807356bb344f.gif)
![Captura de ecrã de 2020-09-28 14-46-14](https://user-images.githubusercontent.com/30150045/94467527-7b963e00-0199-11eb-9ef4-d642caea19ee.png)

**Comment by vinceliuice** [comment]
Assets folder missing or all png files are not readable, you can reinstall this theme again

**Comment by samuelcecilio** [comment]
Thanks!

1. `sudo rm -rf /usr/share/themes/vimix-*`
2. `rm -rf ~/.themes/vimix-*`
3. `sudo ./install.sh`
4. the "icons" do not appear in some apps (gnome-calendar, bleachbit) but appear in others (terminal, settings)
5. `./install.sh`
6. icons appear in all apps

is there a better solution?
