### ISSUE TITLE
勾选框出现了问题

### ISSUE THREAD

**Issue by Tony-AI** [vinceliuice/vimix-gtk-themes#19]
你好，首先很感谢你能够提供这好看的主题，谢谢！但是我使用额过程中出现了一个问题，我使用的是Ubuntu16.10，在安装使用主题之后，所有的勾选框都变成了一个粉红色的方框，但是点击后能够开启或关闭，但是，我无法得知他们的状态，例如“在菜单栏中显示时间”现在是开启的还是关闭的。
![default](https://cloud.githubusercontent.com/assets/17319140/23829899/4e97ff7e-0738-11e7-94b2-0f38eb07ebec.png)
再次感谢你能够提供这个主题，谢谢！

**Comment by vinceliuice** [comment]
出现这种情况一般都是主题使用的图标资源丢失了，你可以去主题目录里看一下图标资源还在不，然后重新安装一下主题

**Comment by Tony-AI** [comment]
好的，我查看一下，谢谢你 ：）

**Comment by Tony-AI** [comment]
问题解决了！我最开始的时候将主题安装在了系统目录，现在我将它卸载后安装到了自己用户的目录下，一切都正常了，再次感谢！
