### ISSUE TITLE
When the theme is not dark, the notification interface plugin is still dark

### ISSUE THREAD

**Issue by suiahae** [vinceliuice/vimix-gtk-themes#192]
When the theme is not dark, the notification interface plugin is still dark in GNOME 3.38.1, like this

![image](https://user-images.githubusercontent.com/45323123/100424318-5f931800-30c8-11eb-987e-c150e63ebdcf.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed
