### ISSUE TITLE
No top nautilus bar background

### ISSUE THREAD

**Issue by tiotrom** [vinceliuice/vimix-gtk-themes#193]
Is this intentional?
![image](https://user-images.githubusercontent.com/34804533/100489465-8f680d00-3114-11eb-8389-fa580a274c60.png)
In Adwaita it looks like this:
![image](https://user-images.githubusercontent.com/34804533/100489487-ac9cdb80-3114-11eb-939f-d93cff0c11a7.png)

In vimix it looks as if something is missing from there

**Comment by vinceliuice** [comment]
Fixed!
