### ISSUE TITLE
Gnome Shell Font with Nerd Font issue

### ISSUE THREAD

**Issue by cdmeister** [vinceliuice/vimix-gtk-themes#197]
Hi,

I am on Ubuntu 20.04 with Gnome Shell 3.36.8. I install the Vimix themes first, then installed the [Nerd font](https://github.com/ryanoasis/nerd-fonts) and it messed up the gnome shell font as soon as I used a vimix shell theme:

![Screenshot from 2021-01-06 13-57-21](https://user-images.githubusercontent.com/12223651/103809532-a65d2180-5027-11eb-8113-6e2217dfaab1.png)

As a work around, I just deleted the following line from the vimix-dark-amethyst/gnome-shell/gnome-shell.css:
`  font-family: "M+ 1c", Roboto, Cantarell, Sans-Serif;`
and that seems to resolve the issue. 

I was just wondering if you knew what what was going on? I assumed after the nerd font installation, it was trying to default to something that rendered the font incorrectly.

**Comment by vinceliuice** [comment]
I'll fix this!
