### ISSUE TITLE
Gedit search bar not displayed properly

### ISSUE THREAD

**Issue by am97** [vinceliuice/vimix-gtk-themes#198]
Hello,

I am on Fedora 33, Gnome 3.38.2 and I installed Vimix by cloning the repo and running `install.sh`. 

The Gedit search bar is not displayed properly, the background is gone:

![Screenshot from 2021-01-10 23-39-10](https://user-images.githubusercontent.com/18473412/104137598-620eb000-539e-11eb-8534-101ef8ae9eb8.png)

I tried checking out to older commits, and found that the commit that causes this issue is https://github.com/vinceliuice/vimix-gtk-themes/commit/8cfdc6070eeb51fcedfc00afd464336751beb7c8

Before that commit, the search bar is displayed correctly:

![Screenshot from 2021-01-10 23-40-02](https://user-images.githubusercontent.com/18473412/104137625-971b0280-539e-11eb-8abf-bed091df5dc1.png)

**Comment by vinceliuice** [comment]
I'll fix this!
