### ISSUE TITLE
Install 腳本誤將 Dark 版的 index.theme 指派給 Light

### ISSUE THREAD

**Issue by cwchien** [vinceliuice/vimix-gtk-themes#2]
您好：
首先感謝您的開源，讓我的 Ubuntu Mate 在 Numix 外還有其它選擇（而我更喜歡 Vimix）

回報一個問題：
在 [Install 腳本第 30 行](https://github.com/vinceliuice/vimix-gtk-themes/blob/master/Install#L30) 並沒有考慮到 `index-Light-*` 的情況
因此 `VimixDark` 和 `VimixLight` 裡的 `index.theme` 其實都是同一組（Dark 版）
造成在佈景主題設定中會看到兩組 `VimixDark-*`（一組是正確的，另一組是 VimixLight 誤植）

建議 Dark 版的 `index.theme` 更改檔名為 `index-Dark-*`
然後將 [Install 腳本第 30 行](https://github.com/vinceliuice/vimix-gtk-themes/blob/master/Install#L30) 改為 `index${variant}${size}${color}.theme`

（不好意思，不太會用 PR，只好用敘述的）

**Comment by vinceliuice** [comment]
非常感谢！写脚本有点粗心了，谢谢你给我找到的错误，我会根据你的建议改正的。

**Comment by cwchien** [comment]
剛有點筆誤 `index${variant}${size}${color}.theme` 應為 `index-${variant}${size}${color}.theme`
我 index 後少寫了一個 dash

**Comment by cwchien** [comment]
不會，麻煩您了：）

預祝新年快樂

**Comment by vinceliuice** [comment]
哈哈！新年快乐！

**Comment by vinceliuice** [comment]
已经修复了

**Comment by vinceliuice** [comment]
这回行了，非常感谢！

**Comment by cwchien** [comment]
真不好意思 .. 打擾了：）
哈哈 .. 多謝

**Comment by vinceliuice** [comment]
没事，没人提醒我的话，我都不知道我要到什么时候才会发现这问题
