### ISSUE TITLE
File manager doesn't look as expected

### ISSUE THREAD

**Issue by kenenbek** [vinceliuice/vimix-gtk-themes#20]
I downloaded `.zip` archive from https://github.com/vinceliuice/vimix-gtk-themes/releases.
Then I run
`./Vimix-installer.sh`
As a result, default file manager looks like that (with paper icons):
http://i.imgur.com/OTEkH9F.png

What do I miss to make it more like as screens from https://camo.githubusercontent.com/1177a26b83a8766b885a7ae051d38d46e45a8f47/68747470733a2f2f636e2e706c696e672e636f6d2f696d672f662f372f652f622f6264343939393335626562643765373730323834346333326237663539613931646431642e6a70673f7261773d74727565

**Comment by cwchien** [comment]
Vimix works for [GTK 3.20 or later](https://github.com/vinceliuice/vimix-gtk-themes#gtk-320-or-later).

If you're using Ubuntu 16.04 (which is GTK 3.18) or before, you need to upgrade your GTK3 runtime.

**Comment by kenenbek** [comment]
I updated gtk+
```
~ ❯❯❯ dpkg -l libgtk2.0-0 libgtk-3-0
  libgtk-3-0:amd64          3.20.8-1ubuntu0~p amd64             GTK+ graphical user interface library
  libgtk2.0-0:amd64         2.24.30-4ubuntu1~ amd64             GTK+ graphical user interface library
```

Then I run './VimixInstaller.sh' again:
But my file managers looks badly: http://i.imgur.com/lUtQBJY.png

**Comment by cwchien** [comment]
1. If you execute the file-manager from terminal, is there any error message ?
2. If you install theme into `/usr/share/themes` with **sudo**, you can try to ensure the file permissions with `sudo chmod 755 /usr/share/themes/VimixDark-Laptop -R` for example.

**Comment by kenenbek** [comment]
```
~ ❯❯❯ gnome-open .
~ ❯❯❯ GDBus.Error:org.freedesktop.DBus.Error.NotSupported: Application does not handle command line arguments

(nautilus:6667): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(nautilus:6667): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

```

**Comment by cwchien** [comment]
Perhaps you can try 

1. logout and  login again to reload GTK theme.
2. [this](http://askubuntu.com/questions/788182/nautilus-not-opening-up-showing-glib-error).

If the instructions don't help, maybe someone else can lend a hand.
(I use MATE desktop and Caja works fine)

**Comment by kenenbek** [comment]
The first option is helped me!
Thanks!!!

**Comment by cwchien** [comment]
No problem. :)
