### ISSUE TITLE
MATE - Caja rename issue with dark themes

### ISSUE THREAD

**Issue by pallebone** [vinceliuice/vimix-gtk-themes#200]
Hello when renaming a file when a dark theme is selected (eg: vimix-dark-laptop) the text of the file you are renaming is not erased/cleared so when you are typing you see characters on top of the name that existed before.

See video
[vokoscreenNG-2021-01-21_14-37-33.mkv.zip](https://github.com/vinceliuice/vimix-gtk-themes/files/5851700/vokoscreenNG-2021-01-21_14-37-33.mkv.zip)

 for example.

I am not able to find inside the theme gtk.css where to modify this behaviour.

Can anyone assist me? Thank you in advance :)

Kind regards
Peter

**Comment by pallebone** [comment]
Just tried the latest build and this is resolved in the latest version of the theme. 
Many thanks :)

Pete

**Comment by vinceliuice** [comment]
You are welcome!
