### ISSUE TITLE
gtk 4 support

### ISSUE THREAD

**Issue by codic12** [vinceliuice/vimix-gtk-themes#206]
Since you added support for your other themes, is it possible to do it in the Vimix theme too if it isn't too much burden? Thanks for all your great work!

**Comment by vinceliuice** [comment]
No problem! I'll make this theme supported

**Comment by vinceliuice** [comment]
Supported now!

**Comment by codic12** [comment]
That's awesome! You're really fast at this, thank you!

**Comment by vinceliuice** [comment]
You are welcome!
