### ISSUE TITLE
Taskbar padding acts weird.

### ISSUE THREAD

**Issue by ClosedSequence** [vinceliuice/vimix-gtk-themes#21]
I've installed Vimix correctly, everything works okay, but the only issue is the padding on the task bar cuts off icons. I have no clue what it's doing. Here's the [image](http://imgur.com/a/kVY7j)

**Comment by vinceliuice** [comment]
Xfce4 you desktop?

**Comment by ClosedSequence** [comment]
LXDE is my desktop, but I have GTK+ installed.
