### ISSUE TITLE
Cancel button overlaps unlock button in lightdm

### ISSUE THREAD

**Issue by rom1v** [vinceliuice/vimix-gtk-themes#215]
Hi,

Firstly, thank you for the theme, it's great!

Just a small bug, on debian sid, with XFCE and lightdm a as locker, the cancel button is partially under the unlock button:

![bug](https://user-images.githubusercontent.com/543275/117577241-4cf62380-b0e9-11eb-8f8c-633a6020ba7a.png)

**Comment by vinceliuice** [comment]
Try the last version

**Comment by rom1v** [comment]
Thank you, fixed :+1:

![fixed](https://user-images.githubusercontent.com/543275/117581789-e3810f80-b0fe-11eb-9e57-8763cb7cee88.png)

**Comment by rom1v** [comment]
(However, I think the padding around the buttons is too big now.)

**Comment by vinceliuice** [comment]
I'll adjust this
