### ISSUE TITLE
GSConnect: No name when more than one device 

### ISSUE THREAD

**Issue by n1c0saurio** [vinceliuice/vimix-gtk-themes#218]
If there are various device connected simultaneously, the names of the devices (and therefore, the battery level) are not showed.

One device connected:
![Captura de pantalla de 2021-05-02 19-29-35](https://user-images.githubusercontent.com/16579247/122658219-9c902c00-d138-11eb-869e-a012649dc507.png)

Two device connected:
![Captura de pantalla de 2021-05-02 00-24-15](https://user-images.githubusercontent.com/16579247/122658226-ae71cf00-d138-11eb-9941-45ed6080b052.png)

And I noticed this happens too when you attach it to the panel:
![Captura de pantalla de 2021-05-02 00-23-57](https://user-images.githubusercontent.com/16579247/122658269-2fc96180-d139-11eb-91e7-703f4338c0e9.png)

**Comment by vinceliuice** [comment]
Only this theme have this issue?

**Comment by n1c0saurio** [comment]
Sorry for the delay...

Yes, here are a screenshot with default shell theme:
![Captura de pantalla de 2021-06-21 10-31-22](https://user-images.githubusercontent.com/16579247/122780737-1df0d700-d27d-11eb-8507-03505101ad6f.png)

And here with Yaru:
![Captura de pantalla de 2021-06-21 10-33-13](https://user-images.githubusercontent.com/16579247/122781025-6a3c1700-d27d-11eb-97cb-903ff282efdb.png)

**Comment by vinceliuice** [comment]
I'll check this!
