### ISSUE TITLE
Firefox radio-buttons bug?

### ISSUE THREAD

**Issue by fblais** [vinceliuice/vimix-gtk-themes#219]
Hi.
Running the latest Vimix version on Debian Bullseye Gnome.
Doder color, flat window decorations (-f install option).
Laptop variant for the application, regular variant for Gnome shell.
Firefox 78.11.0 ESR.

I see this:
![image](https://user-images.githubusercontent.com/28492426/125004364-605d3680-e027-11eb-88a6-b247db93fd85.png)

The radio-buttons are misaligned with the text.

Thanks in advance!

**Comment by vinceliuice** [comment]
Fixed!
