### ISSUE TITLE
GNOME Panel shadow in maximized view

### ISSUE THREAD

**Issue by Feichtmeier** [vinceliuice/vimix-gtk-themes#22]
Hi and thanks for this awesome theme!
Would it be possible to remove that shadow under the GNOME panel? It is distracting especially when you have your window maximized.

GNOME 3.24 Ubuntu GNOME 17.04
![bildschirmfoto von 2017-04-17 18-41-37](https://cloud.githubusercontent.com/assets/15329494/25095861/be20474e-239d-11e7-94b6-cc52e27c7c36.png)

GTK Theme Vimix Dark
Shell Theme Vimix Dark

**Comment by vinceliuice** [comment]
If you don't like it you can edit /vimix-gtk-themes/src/gnome-shell/sass/_common.scss,  
(about 835 line)
-----------------------------------------------------
/* TOP BAR */

#panel {
  background-color: $topbar_color;
  font-weight: bold;
  height: $menuitem_size;
  box-shadow: 0px 1px 2px 1px rgba(0,0,0,0.35); 
------------------------------------------------------
Just remove :  box-shadow: 0px 1px 2px 1px rgba(0,0,0,0.35);  and run /vimix-gtk-themes/parse-sass.sh ,
you will get the non-shadow on topbar of gnome-shell one.
But before you do this , you should make sure you have install ruby, gem, sass & bundle.
you can run " sudo apt install ruby-sass ruby-bundler " to install them.

**Comment by vinceliuice** [comment]
Hope it'll help!

**Comment by Feichtmeier** [comment]
Thanks for the reply. Can I somehow edit the current gtk theme in use?

**Comment by vinceliuice** [comment]
Of course you can
