### ISSUE TITLE
checkbox buttons hover highlight is truncated

### ISSUE THREAD

**Issue by fossfreedom** [vinceliuice/vimix-gtk-themes#223]
![image](https://user-images.githubusercontent.com/996240/130579016-9ec79a35-c614-4d92-b9b3-c06dff7af938.png)

Not sure on the best way to resolve this.

So for apps that have multiple checkboxes in a grid (in this case budgie desktop - weathershow applet) the top-bottom checkbox hover highlight is truncated.

The highlight slightly overlaps the label of the checkbox as well.

I suppose a margin factor could be used here to resolve the truncation?  No sure if anything can be done for the label.

Likewise since where the checkbox is left-most position in a grid, the highlight is also truncated

Ubuntu Budgie 21.04/21.10, Vimix (all variants) release tag 2021-08-17

**Comment by vinceliuice** [comment]
I'll try add some margin to the left

**Comment by vinceliuice** [comment]
I think this is fixed
