### ISSUE TITLE
when shell theme is vimix-light-beryl, the gnome top is no longer translucent

### ISSUE THREAD

**Issue by Sherlock-Holo** [vinceliuice/vimix-gtk-themes#224]
before I updated to the latest commit(ccb40da), my GNOME top is translucent with shell theme vimix-light-beryl, but after the update, the top is no longer translucent, instead, it's white color.

I notice when I roll back to the commit(fdf3ea6), it becomes back translucent

**Comment by vinceliuice** [comment]
Now you can run `./install.sh -tweaks translucent` to get this version

**Comment by vinceliuice** [comment]
Choose the `vimix-beryl` version, now this one is translucent black panel with white popover menu

**Comment by Sherlock-Holo** [comment]
@vinceliuice after install with `-tweaks translucent` and choose `vimix-beryl` version, the top is translucent now, but when I press `Win` and see the windows, the background of window's name is white, and the text is also white, it's a little difficult to read the text
![2021-09-05 15-09-42 的屏幕截图](https://user-images.githubusercontent.com/10096425/132118624-af7a156b-f9dc-4ca5-8d74-59745ff13727.png)

**Comment by vinceliuice** [comment]
Now it's fixed!
