### ISSUE TITLE
background issues for some widget

### ISSUE THREAD

**Issue by sigzegv** [vinceliuice/vimix-gtk-themes#230]
I updated this theme on my system some days ago on ubuntu 20.04 (gnome 36), I checked the screenshot in the readme with the examples : 
![image](https://user-images.githubusercontent.com/6304596/146096684-0d711f41-c408-40aa-bc5b-922a63bc5f93.png)

I am using the **dark-compact-ruby** variant, and on my system some widgets like list dropdown, or the +/- counter doesnt' display their background correctly, something is missing : 
![image](https://user-images.githubusercontent.com/6304596/146096705-040ae998-4613-4abc-bea7-a03ef32d11dc.png)

I still have and old variant called **dark-laptop-ruby** that doesn't have such issues, so I was wondering why a newer version may have an issue ?

**Comment by vinceliuice** [comment]
No issue, just changed the style
