### ISSUE TITLE
Update to cinnamon theme 5.2

### ISSUE THREAD

**Issue by Initu-Castilhos** [vinceliuice/vimix-gtk-themes#231]
Update to cinnamon theme 5.2

**Comment by KR4U7H3R** [comment]
First of all thank you for the great theme. I am currently using Cinnamon 5.4 and the only thing I noticed is that the Calender applet seems not to look as expected. So there are no icons on the days with appointments and also the appointments are not displayed as in other/standard themes. Even outdated themes display this correctly, so I hope the effort should be not to high.
