### ISSUE TITLE
it seems there is a little compatible problem with gnome 42

### ISSUE THREAD

**Issue by Sherlock-Holo** [vinceliuice/vimix-gtk-themes#233]
![截图 2022-04-13 22-45-34](https://user-images.githubusercontent.com/10096425/163207401-00a0088e-963b-45f3-9c93-c8c4f10ced42.png)

after update to gnome 42, the settings use the default theme, not the vimix theme

**Comment by Sherlock-Holo** [comment]
I use the `./install.sh -tweaks translucent` to install the translucent version, after use the latest commit, the 
![image](https://user-images.githubusercontent.com/10096425/164912257-6c252ef8-172a-4983-bb5a-284603e2f704.png)
is fixed, but the gnome settings is no changed 
![image](https://user-images.githubusercontent.com/10096425/164912271-db09cd42-4f1d-448b-9664-eaefe1616247.png)

I have pressed the `alt+f2` and enter `r` to restart gnome-shell, should I need to restart the system to make the theme take effect?

**Comment by vinceliuice** [comment]
现在修复啦

**Comment by Sherlock-Holo** [comment]
> 现在修复啦

![image](https://user-images.githubusercontent.com/10096425/164980079-5b6b23b9-aeaa-499b-a150-a75da317f4c3.png)

well...I think the theme works on gtk4 now, but it seems the color is a little different between gtk3 app and gtk4?

**Comment by vinceliuice** [comment]
不能跟随设置切换的，你安装的时候是什么主题，libadwaita就用什么主题，因为libadwaita并不支持更换主题，你要beryl的话就运行： ./install.sh -t beryl -c light

**Comment by Sherlock-Holo** [comment]
> 不能跟随设置切换的，你安装的时候是什么主题，libadwaita就用什么主题，因为libadwaita并不支持更换主题，你要beryl的话就运行： `./install.sh -t beryl -c light`

is there any way to switch the theme after install? if not, that's a bad news for gnome 42...

**Comment by Sherlock-Holo** [comment]
[PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vimix-gtk-themes-translucent-git#n29) that's the PKGBUILD I write to create the arch package with all themes

**Comment by vinceliuice** [comment]
The install.sh just link the theme to gtk-4.0 config file, so if you want change the theme for libadwaita, you need to run the install.sh to install the theme you selected again to relink it
----------
```
  # link gtk4.0 for libadwaita
  mkdir -p                                                                              ${HOME}/.config/gtk-4.0
  rm -rf ${HOME}/.config/gtk-4.0/{assets,gtk.css,gtk-dark.css}
  ln -sf ${THEME_DIR}/gtk-4.0/assets                                                    ${HOME}/.config/gtk-4.0/assets
  ln -sf ${THEME_DIR}/gtk-4.0/gtk.css                                                   ${HOME}/.config/gtk-4.0/gtk.css
  ln -sf ${THEME_DIR}/gtk-4.0/gtk-dark.css                                              ${HOME}/.config/gtk-4.0/gtk-dark.css
```
