### ISSUE TITLE
Mate Caja rename cursor invisible

### ISSUE THREAD

**Issue by yeezy69** [vinceliuice/vimix-gtk-themes#235]
I use a vimix dark theme since one year. The cursor when renaming files in caja is barely visible for me. The problem exists in the 2021 versions as well as in the current 2022-04-24. Is this a bug or maybe i did something wrong?

![Screenshot_001](https://user-images.githubusercontent.com/22444686/165107677-2f3047f1-0e53-439c-b633-7c90d3910b9d.png)

**Comment by vinceliuice** [comment]
Fixed!
