### ISSUE TITLE
missing compact variants

### ISSUE THREAD

**Issue by fossfreedom** [vinceliuice/vimix-gtk-themes#237]
Hi,

  just trying to debian package this.  I note that "laptop" has now changed to "compact".  Fair enough.

when I run ./install.sh -a
I get all the colour & theme variants but I dont get the standard and compact size variants.

In the last release I saw all colour & theme variants and both size variants as well.

Is this expected?  if this is a change then the ../install.sh needs a tweak not to say that it defaults to all sizes

**Comment by KR4U7H3R** [comment]
Is there still being worked on the package for Debian? Would be a nice thing.

As of your question. ./install.sh -a I just got all colour and theme variants installed at once.

**Comment by vinceliuice** [comment]
Run `./install.sh -s compact` to install compact version

Run `./install.sh -t all -s all` to install all themes

**Comment by fossfreedom** [comment]
hi @vinceliuice 

for our debian package I've modified the rules as you have recommended - but this is the output:

/install.sh -s compact -d "/<<PKGBUILDDIR>>/debian/Vimix"
'gnome-shell' not found, using styles for last gnome-shell version available.
Installing '/<<PKGBUILDDIR>>/debian/Vimix/vimix-compact-doder'...
Install compact version ...
Installing '/<<PKGBUILDDIR>>/debian/Vimix/vimix-light-compact-doder'...
Install compact version ...
Installing '/<<PKGBUILDDIR>>/debian/Vimix/vimix-dark-compact-doder'...
Install compact version ...

Done.
./install.sh -t all -s all -d "/<<PKGBUILDDIR>>/debian/Vimix"
'gnome-shell' not found, using styles for last gnome-shell version available.
ERROR: Unrecognized theme variant 'all'.
Try './install.sh --help' for more information.
make[1]: *** [debian/rules:9: override_dh_auto_configure] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:4: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

Any ideas about the "all" parameter issue above?

**Comment by vinceliuice** [comment]
![截图 2023-01-25 23-52-07](https://user-images.githubusercontent.com/7604295/214610472-ee6f030d-fc17-4ce8-8214-d0c651de1830.png)
It works on my desktop

**Comment by fossfreedom** [comment]
thx. Install is ok now.  I've rebuilt the debian package and is now available for all budgie lunar users. Cheers again.
