### ISSUE TITLE
Strange line in Gnome text editor while using Vimix

### ISSUE THREAD

**Issue by Raxelgrande** [vinceliuice/vimix-gtk-themes#254]
Tried with Vimix Jade and Ruby.
When you launch gnome-text-editor, every time you stop typing, a line appears in the first row of text. Pay close attention and you will see it. 
It's worth noting that when you save a document, a similar line (colored corresponding to the theme) appears. Using Adwaita, the line only appears when you save the text file.
[Grabación de pantalla desde 2023-05-17 22-01-51.webm](https://github.com/vinceliuice/vimix-gtk-themes/assets/93939943/f0db63b1-80eb-4a58-8b88-939164d3ffc9)

**Comment by vinceliuice** [comment]
Fixed now!
