### ISSUE TITLE
GIMP window decorations diasppear

### ISSUE THREAD

**Issue by githubbbbbbbbb** [vinceliuice/vimix-gtk-themes#255]
Hello, there's an issue with windows decorations in e.g. GIMP, they disappear sometimes. I mean they become invisible but you can close the window pressing where the close button should be, but the headerbar is just transparent. It sometimes happens with other apps.
I'm using Debian Bookworm fully upgraded.
![Снимок экрана от 2023-06-19 13-29-14](https://github.com/vinceliuice/vimix-gtk-themes/assets/66219558/905ec2d1-379e-49c2-a994-6b6ee1feeb2b)

**Comment by githubbbbbbbbb** [comment]
probably it is not the theme issue but this - https://gitlab.gnome.org/GNOME/mutter/-/issues/2725
Strange thing that titlebar appears when I switch theme to e.g. Orchis and disappears when switch back to Vimix

**Comment by vinceliuice** [comment]
Try the last update

**Comment by githubbbbbbbbb** [comment]
It is still the same with the latest version
![Снимок экрана от 2023-06-21 11-39-53](https://github.com/vinceliuice/vimix-gtk-themes/assets/66219558/e7535c57-9797-4cc6-ae76-87af64739a78)

**Comment by githubbbbbbbbb** [comment]
same issue after the latest commits. But while using Orchis theme everything is ok so it is definetely vimix issue

**Comment by vinceliuice** [comment]
This is my desktop, all works well, what's your gnome version ?

**Comment by githubbbbbbbbb** [comment]
it's gnome 43.6 and I have this issue only using Vimix theme. Probably no need to waste your time if is not replicatable

**Comment by githubbbbbbbbb** [comment]
found how to fix it: 
autoclose-xwayland option in dconf is to blame. After the fitst launch and exit of any xwayland app - xwayland cannot be respawned next time it is launched. So disabling autoclose xwayland fixes the error. Dunno why it was like that only with Vimix
![Снимок экрана от 2023-06-27 00-37-23](https://github.com/vinceliuice/vimix-gtk-themes/assets/66219558/8741db65-0f2e-4c4e-8ecc-148614f6fc8b)
