### ISSUE TITLE
Request: Dark background variant

### ISSUE THREAD

**Issue by luisfpg** [vinceliuice/vimix-gtk-themes#26]
First, thanks for the Vimix themes, they look very nice!
I would like to request for a dark background variant, which would apply to GTK2, as well as GTK3 (without the prefer global dark theme setting), using the same colors as gtk-dark.css (for GTK3).

**Comment by buncismamen** [comment]
Yeah I think it's bug for mate, apparently this theme have no black background theme.

is there any workaround to achieve this for now?
