### ISSUE TITLE
nautilus and setting color is incorrect when using the beryl theme

### ISSUE THREAD

**Issue by Sherlock-Holo** [vinceliuice/vimix-gtk-themes#260]
![image](https://github.com/vinceliuice/vimix-gtk-themes/assets/10096425/df18a63b-628f-4a4d-857b-3dce63dcde75)
![image](https://github.com/vinceliuice/vimix-gtk-themes/assets/10096425/2691811a-cb8e-459c-a6d4-bff9d84c84b3)

the title bar should be black like

![image](https://github.com/vinceliuice/vimix-gtk-themes/assets/10096425/02250b1b-af6f-41e0-b895-47bc91d523ad)

in `~/.config/gtk-4.0`, the theme is set `beryl`
```
ll ~/.config/gtk-4.0
总计 20K
drwx------ 1 sherlock sherlock   74  1月 3日 10:28 ./
drwx------ 1 sherlock sherlock 1.7K 12月28日 14:33 ../
lrwxrwxrwx 1 sherlock sherlock   44  1月 3日 10:28 assets -> /usr/share/themes/vimix-beryl/gtk-4.0/assets/
lrwxrwxrwx 1 sherlock sherlock   45  1月 3日 10:28 gtk.css -> /usr/share/themes/vimix-beryl/gtk-4.0/gtk.css
lrwxrwxrwx 1 sherlock sherlock   50  1月 3日 10:28 gtk-dark.css -> /usr/share/themes/vimix-beryl/gtk-4.0/gtk-dark.css
```

**Comment by Sherlock-Holo** [comment]
when I run nautilus in console, it show

> ** Message: 10:35:44.014: Connecting to org.freedesktop.Tracker3.Miner.Files
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.025: Theme parser error: gtk.css:4932:21-28: Expected a valid color.
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.025: Theme parser error: gtk.css:4937:21-28: Expected a valid color.
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.025: Theme parser error: gtk.css:5091:21-28: Expected a valid color.
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.025: Theme parser error: gtk.css:5097:21-28: Expected a valid color.
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.026: Theme parser error: gtk.css:6334:16-17: Expected a number
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.027: Theme parser error: gtk.css:6518:22-27: Junk at end of value for outline-width
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.041: Theme parser error: gtk.css:4932:21-28: Expected a valid color.
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.041: Theme parser error: gtk.css:4937:21-28: Expected a valid color.
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.041: Theme parser error: gtk.css:5091:21-28: Expected a valid color.
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.041: Theme parser error: gtk.css:5097:21-28: Expected a valid color.
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.042: Theme parser error: gtk.css:6334:16-17: Expected a number
> 
> (org.gnome.Nautilus:595774): Gtk-WARNING **: 10:35:44.042: Theme parser error: gtk.css:6518:22-27: Junk at end of value for outline-width

**Comment by Sherlock-Holo** [comment]
> 1月 11 10:41:50 sherlokyang-LC1 nautilus[391680]: Theme parser error: gtk.css:4932:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 nautilus[391680]: Theme parser error: gtk.css:4937:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 nautilus[391680]: Theme parser error: gtk.css:5091:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 nautilus[391680]: Theme parser error: gtk.css:5097:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 gnome-clocks[391690]: Theme parser error: gtk.css:4932:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 gnome-clocks[391690]: Theme parser error: gtk.css:4937:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 gnome-clocks[391690]: Theme parser error: gtk.css:5091:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 gnome-clocks[391690]: Theme parser error: gtk.css:5097:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 gnome-control-c[391688]: Theme parser error: gtk.css:4932:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 gnome-control-c[391688]: Theme parser error: gtk.css:4937:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 gnome-clocks[391690]: Theme parser error: gtk.css:6334:16-17: Expected a number
> 1月 11 10:41:50 sherlokyang-LC1 gnome-clocks[391690]: Theme parser error: gtk.css:6518:22-27: Junk at end of value for outline-width
> 1月 11 10:41:50 sherlokyang-LC1 gnome-control-c[391688]: Theme parser error: gtk.css:5091:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 gnome-control-c[391688]: Theme parser error: gtk.css:5097:21-28: Expected a valid color.
> 1月 11 10:41:50 sherlokyang-LC1 nautilus[391680]: Theme parser error: gtk.css:6334:16-17: Expected a number
> 1月 11 10:41:50 sherlokyang-LC1 nautilus[391680]: Theme parser error: gtk.css:6518:22-27: Junk at end of value for outline-width
> 1月 11 10:41:50 sherlokyang-LC1 gnome-control-c[391688]: Theme parser error: gtk.css:6334:16-17: Expected a number
> 1月 11 10:41:50 sherlokyang-LC1 gnome-control-c[391688]: Theme parser error: gtk.css:6518:22-27: Junk at end of value for outline-width

I found this log in journactl

**Comment by Sherlock-Holo** [comment]
commit cc919536 doesn't have this problem

**Comment by Rodancoci** [comment]
Same problem using vimix-doder. I don't get any errors when launching nautilus from the terminal though.

Running on Arch, GNOME 45.5 and using `vimix-gtk-themes-git` from the AUR.

![TopBar](https://github.com/vinceliuice/vimix-gtk-themes/assets/11667577/2aaba017-7b26-469b-979e-378e2760cf15)

**Comment by Rodancoci** [comment]
There's also something strange going on with modal dialogs. Here's what it looks like when I try to empty my trash:

![image](https://github.com/vinceliuice/vimix-gtk-themes/assets/11667577/5ef69482-efbe-41d4-a9a8-f1fd14ca81e4)
