### ISSUE TITLE
Cinnamon - Nemo 6.0.2: Sidebar too shrunk

### ISSUE THREAD

**Issue by ding0z** [vinceliuice/Vimix-gtk-themes#264]
![Screenshot 2024-06-04 at 12 55 06](https://github.com/vinceliuice/vimix-gtk-themes/assets/59647128/35b891c3-fa0f-4ea5-85c0-5efbdd4ef605)
Hi,

The list of items in the sidebar as well as the main window doesn't have enough padding between the items. The result is they are too shrunk to each other.

Is there a way to apply the original padding and font size?

Thanks.

**Comment by fblais** [comment]
I agree with this comment.
FWIW, McMojave and WhiteSur are having the same issue with Nemo.
Thanks in advance!

**Comment by fblais** [comment]
Thanks!
