### ISSUE TITLE
Selection highlight in firefox navigation bar is barely visible

### ISSUE THREAD

**Issue by Mentis** [vinceliuice/vimix-gtk-themes#31]
Selection highlight in firefox navigation bar is barely visible
![screenshot from 2017-08-06 23-47-17](https://user-images.githubusercontent.com/273806/29015133-9dbaf8c6-7b01-11e7-8c60-f11c0a31a38a.png)

In compassing Deepin theme:
![default](https://user-images.githubusercontent.com/273806/29015163-c0c33a5e-7b01-11e7-9cfa-0338825546f3.png)

**Comment by vinceliuice** [comment]
I fixed this， Now is ok with Firefox
