### ISSUE TITLE
Conflicting problem with gnome-shell-extension-maximized-by-default

### ISSUE THREAD

**Issue by Warmuser** [vinceliuice/vimix-gtk-themes#33]
Hello, I think your theme conflicts in someway with the GNOME extension called Maximized by Default, i tried with all the variants and the problem persists. :) Here is the video demostration: https://www.youtube.com/watch?v=asrzJoHNx2M

PS: I submitted the issue also to the extension developer.

**Comment by vinceliuice** [comment]
Sorry I don't get the issue on my desktop, Maximized by Default works well on my ubuntu 17.04

**Comment by Warmuser** [comment]
There is someway to fix it?

**Comment by vinceliuice** [comment]
It's the issue of gnome-shell-extension-maximized-by-default, I really don't know how to do with it

**Comment by Warmuser** [comment]
Ok, anyway I posted an issue to the other developer. Thank you! :)

**Comment by Warmuser** [comment]
I want also to submit a request, can you please add a Vimix theme for Plank?
