### ISSUE TITLE
Broken layout on Ubuntu

### ISSUE THREAD

**Issue by yoshida7** [vinceliuice/vimix-gtk-themes#36]
I've followed all steps, but when I enable this theme, the File manager and other places looks strange (look on the left side), check image attached. Am I missing something? Thanks!

**OS:** Ubuntu 16.04 LTS

![screenshot from 2017-09-06 14-02-25](https://user-images.githubusercontent.com/30873769/30124617-18f4fcf4-930c-11e7-9dc4-c3a9e25fbca9.png)

**Comment by vinceliuice** [comment]
Sorry, the default gtk version of ubuntu 16.04 is gtk3.18，But my theme only support gtk 3.20 or later desktops， so if you want to use this theme you should update your gnome base version：

> sudo add-apt-repository ppa:gnome3-team/gnome3-staging
> sudo add-apt-repository ppa:gnome3-team/gnome3
> sudo apt-get update
> sudo apt-get dist-upgrade

**Comment by yoshida7** [comment]
@vinceliuice hey thanks for the reply, I didn't know that sorry. I'll try it now and I'll update here with the results.

**Comment by vinceliuice** [comment]
The png files missing, You can reinstall it.

**Comment by yoshida7** [comment]
Is there a way to install png files manually? I tried to remove and install theme again and it still persists

**Comment by yoshida7** [comment]
Thanks it worked :)
