### ISSUE TITLE
month text shows incompletely

### ISSUE THREAD

**Issue by IsoaSFlus** [vinceliuice/vimix-gtk-themes#37]
![image](https://user-images.githubusercontent.com/5125031/30467497-98620f3c-99aa-11e7-849e-d5919de37bda.png)

font:Noto Sans CJK SC(not only)
theme:all the vimix-laptop themes

**Comment by vinceliuice** [comment]
Thanks for you feedback， I‘ll fix soon。

**Comment by vinceliuice** [comment]
Now！ it fixed.
