### ISSUE TITLE
Something wrong in chrome GTK theme!!!

### ISSUE THREAD

**Issue by devillove084** [vinceliuice/vimix-gtk-themes#39]
When i use Vimix-laptop-* themes for chrome,i use mouse right button,but i can not see the second menu bar , so i change another gtk theme, the problem is gone........But i think this gtk theme is more beautiful than other themes which i have use before.So......................................I want your team can see this problem and fix this.Thank you very much!!!!!!!!!!!!!

**Comment by devillove084** [comment]
![screenshot from 2017-09-29 12-09-27](https://user-images.githubusercontent.com/15782923/31000891-da260794-a511-11e7-8405-5d4dcda1bddd.png)

![screenshot from 2017-09-29 12-09-27](https://user-images.githubusercontent.com/15782923/31000891-da260794-a511-11e7-8405-5d4dcda1bddd.png)




![screenshot from 2017-09-29 12-09-14](https://user-images.githubusercontent.com/15782923/31000629-a3f68a42-a50f-11e7-8a67-796f0bcbb47a.png)

**Comment by devillove084** [comment]
Your theme can not see the "Forward" memu in the right button on chrome !I guess some wrong on the gtk.css file but i don't know how to change it.....

**Comment by devillove084** [comment]
By the way , i test Vimix-laptop-doder theme!!

**Comment by vinceliuice** [comment]
![2017-09-29 13-25-02](https://user-images.githubusercontent.com/7604295/31001990-4bd4d8b8-a51a-11e7-9c90-415a2a3bc3ff.jpg)
But I don't get anything wrong with vimix on my desktop

**Comment by devillove084** [comment]
![screenshot from 2017-10-03 20-19-28](https://user-images.githubusercontent.com/15782923/31124901-eecfcef4-a878-11e7-8943-1269e27d53ec.png)

![screenshot from 2017-10-03 20-19-17](https://user-images.githubusercontent.com/15782923/31124843-bd1026e8-a878-11e7-873e-fe87c8f8f308.png)
The problem still  here!!

**Comment by devillove084** [comment]
I really like your Google like theme . So i wish you can see these questions. I use Ubuntu 17.10,gnome 3.26.1, chrome 61.0.3163.100 environment.  The same qusetion on right button menu,one is on chrome,another is on desktop. May be you have to fix some problem on font color and button menu!!

**Comment by devillove084** [comment]
???????

**Comment by vinceliuice** [comment]
Sorry about this, I did not see it until today, I will fix this! Thanks any way!
