### ISSUE TITLE
Vimix-installer script

### ISSUE THREAD

**Issue by DarthWound** [vinceliuice/vimix-gtk-themes#40]
Hello there :)

For people using command line, there's something wrong.
Instructions are that we have to run "./Vimix-installer.sh" but file doesn't have the ".sh" part.

Here's what you have to do if you install Vimix with terminal.
Third line is the important one, you have to rename the script using "mv".
```
git clone https://github.com/vinceliuice/vimix-gtk-themes.git
cd vimix-gtk-themes/
mv Vimix-installer Vimix-installer.sh
./Vimix-installer.sh
```

To @vinceliuice you should rename the file next time :)

**Comment by vinceliuice** [comment]
Thanks for your remind, I will rename this.
