### ISSUE TITLE
Look at the Minimize/Maximize button

### ISSUE THREAD

**Issue by Ufeldraku** [vinceliuice/vimix-gtk-themes#41]
[https://imgur.com/gallery/dttJo](Image)

Gnome 3.26 
Gtk3 = 3.22.24+80+g6a4be7f56b-1
Chromium = 62.0.3202.62-1, just updated.

Doesn't happen with Adwaita.

**Comment by erikkallen** [comment]
I can confirm this

**Comment by phpbugcn** [comment]
have you tried to fix it ???

**Comment by vinceliuice** [comment]
Sorry about this! I still have no idea how to fix this

**Comment by vinceliuice** [comment]
Finally fixed this bug

**Comment by erikkallen** [comment]
Awesome thanks!
