### ISSUE TITLE
On hidpi 2x scaled display, oversized check-boxes.

### ISSUE THREAD

**Issue by Hallelouia** [vinceliuice/vimix-gtk-themes#46]
I use a QHD+ display (3200x1800) on my laptop with hiDPI setting (scaled by a factor of 2).
This result in check boxes being way too big.
Screenshots : 
* vimix dark ruby theme :
![vimix-checkboxes-2x](https://user-images.githubusercontent.com/4830658/32883964-24483c80-cab9-11e7-903e-19b41b0c6eda.png)

* arc dark theme (for comparison) :
![arc-checkboxes-2x](https://user-images.githubusercontent.com/4830658/32883987-3449b62c-cab9-11e7-81cb-78a7564c1f48.png)

EDIT: Radio buttons are equally oversized.

Both screenshots are taken from the same web page in firefox nightly 59.
link for testing : [materiel.net](https://www.materiel.net/pc-portable/) /!\ it's in french.
DE/WM: Cinnamon 3.6
OS: Fedora27 (was identical in 26)

**Comment by zack** [comment]
Also seeing this on:

Monitor: 1080p
Env: Gnome3
OS: Ubuntu 17.10
Browser: FF Dev 58.0b6

Looks like it was also a problem with materia: https://github.com/nana-4/materia-theme/issues/168

**Comment by syskill** [comment]
MEE TO — I've been seeing this problem in Firefox since I updated to release 58.

**Comment by vinceliuice** [comment]
@syskill this bug should be fixed now.
