### ISSUE TITLE
Close opening document button error in LibreOffice

### ISSUE THREAD

**Issue by thachngopl** [vinceliuice/vimix-gtk-themes#49]
See screenshot. No error with Adwaita theme.
![screenshot from 2017-12-19 15-32-52](https://user-images.githubusercontent.com/16706272/34148056-6e9d3046-e4d2-11e7-891d-129a5b8d52c6.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed now!
