### ISSUE TITLE
Vimix-installer fails to check result code of ./Install

### ISSUE THREAD

**Issue by minexew** [vinceliuice/vimix-gtk-themes#5]
```
Installing Vimix...
./Vimix-installer.sh: line 235: ./Install: Permission denied

Installation complete!
```

**Comment by vinceliuice** [comment]
Give the /Install file execute permission

**Comment by minexew** [comment]
I did and that indeed fixed the issue, but the top-level script shouldn't say "installation complete" when it, in fact, failed :)

**Comment by vinceliuice** [comment]
Well！ thanks, I get it now, I'll fix this.
