### ISSUE TITLE
application cannot work with the vimix theme

### ISSUE THREAD

**Issue by Madogtor** [vinceliuice/vimix-gtk-themes#51]
I installed an application(youdao-dict), however it can not work. some information are posted, hope to help you to solve the problem.

My OS is Manjaro Linux 64bit. I love the theme.

--------------------------------
****** in ~ λ youdao-dict
qt5ct: using qt5ct plugin
Youdao Dict Unique Service is started...
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

(python3:6842): Gtk-WARNING **: Theme directory mimetypes/symbolic of theme Vimix has no size field

(python3:6842): Gtk-WARNING **: Theme directory places/symbolic of theme Vimix has no size field

(python3:6842): Gtk-WARNING **: Theme directory 22x22@2x/animations of theme Paper-Vimix has no size field

(python3:6842): Gtk-WARNING **: Theme directory 22x22@2x/panel of theme Paper-Vimix has no size field

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
qt5ct: D-Bus system tray: no
*** Error in `python3': free(): invalid pointer: 0x00007f49637fb3c0 ***
[1]    6842 abort (core dumped)  youdao-dict
---------------------------------------------------------

**Comment by vinceliuice** [comment]
Please download the last version and use the install script to reinstall this theme and try again
