### ISSUE TITLE
Dolphin Emulator throws an error when I use VimixDark theme

### ISSUE THREAD

**Issue by suzil** [vinceliuice/vimix-gtk-themes#52]
```
$ dolphin-emu

** (dolphin-emu:15150): WARNING **: Invalid borders specified for theme pixmap:
        /home/suzil/.themes/VimixDark/gtk-2.0/assets/notebook-combo-entry-ltr-entry.png,
borders don't fit within the image
```

![cant_read](https://user-images.githubusercontent.com/13723264/34414937-52caba02-ebec-11e7-9e37-17b55292beb2.png)

Is this a problem with the Dolphin emulator or with the VimixDark theme?

**Comment by vinceliuice** [comment]
Sorry! I really don't know about this, but this gtk2 theme still works well with gtk2 softwares
