### ISSUE TITLE
Thunderbird - Check Box issue in Menus

### ISSUE THREAD

**Issue by pkomur** [vinceliuice/vimix-gtk-themes#53]
In Menu and Context Menu text overlays Check Boxes. (Ubuntu 17.10, GNOME 3.26.2, Thunderbird 52.5.0, Theme: VimixLight-Laptop-Doder)

![img_20171229_163431322_hdr](https://user-images.githubusercontent.com/11897534/34440748-a16665e6-ecb7-11e7-8f5a-336ede92755f.jpg)
![img_20171229_163530638](https://user-images.githubusercontent.com/11897534/34440750-a1905c66-ecb7-11e7-8c9c-356afb638cef.jpg)

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by pkomur** [comment]
Thanks, but there is one more issue. Disabled menu items have the same colour like enabled items. They should have grey colour, like menu icons.

![zrzut ekranu z 2017-12-30 23-00-53](https://user-images.githubusercontent.com/11897534/34457615-2f67b5da-edb6-11e7-801b-828cfa73d134.jpg)

**Comment by vinceliuice** [comment]
Sorry! fixed now

**Comment by pkomur** [comment]
Now is great! Thanks.
