### ISSUE TITLE
Menu items too high

### ISSUE THREAD

**Issue by pkomur** [vinceliuice/vimix-gtk-themes#54]
In my opinion menu items are too high. Please compare to Azure theme - there are lower, so there are look better.

VimixLight-Laptop:
![zrzut ekranu z 2017-12-30 vimix](https://user-images.githubusercontent.com/11897534/34461407-30ea11f0-ee29-11e7-9a48-03660eeeec22.jpg)

Azure-solid-light:
![zrzut ekranu z 2017-12-30 azure](https://user-images.githubusercontent.com/11897534/34461411-58d2619a-ee29-11e7-9b41-b357db84f5ae.jpg)

**Comment by vinceliuice** [comment]
Fixed now

**Comment by pkomur** [comment]
I meant to decrease _min-height_ value in Menus section for _.menubar > menuitem_ and _.context-menu menuitem_ from **20px** to **18px** for laptop variants.
