### ISSUE TITLE
Weird lines around/in PCManFM

### ISSUE THREAD

**Issue by davidarrieta** [vinceliuice/vimix-gtk-themes#55]
First of all, **I hope you have an excellent and prosperous new year.** I also wanted to **thank you for doing such a good job with Vimix.** A few days ago I discovered Vimix looking for a replacement for the already widely used Arc Flatabulous and I just fell in love ^-^

Having said that, I recently tested Vimix on PCManFM and found [this weird bug](https://imgur.com/a/gJvyq) shortly after opening PCManFM. Those lines sometimes appear and sometimes they don't.

I tried other Vimix variants (I'm currently using Vimix Light Doder) but the bug keeps coming up.
I tried the gtk2 version of PCManFM and naturally the bug doesn't show up, but Vimix just doesn't look like it should.

It is worth mentioning that i'm currently using Arch Linux with i3-gaps, gtk3 3.22 , gtk-engine-murrine 0.98.2 and gtk-engines 2.21.0

**Comment by vinceliuice** [comment]
This is not a bug, It is the overflow transition color
