### ISSUE TITLE
Firefox margin issue with radio buttons

### ISSUE THREAD

**Issue by Artusamak** [vinceliuice/vimix-gtk-themes#57]
Hello,

Thank you for your great work, i really love the style of the theme. :)

I wanted to report a major issue with radio buttons on Firefox.

This is the same page rendered with Firefox & Chromium.
![capture du 2018-01-31 09-29-53](https://user-images.githubusercontent.com/201299/35614525-b0248546-066f-11e8-892b-a77b5f72e830.png)

As you can see, on Firefox, there is a floating issue for multiple radio buttons that shifts the following buttons.
This is a major issue because it breaks sites rendering.

I don't know if it's possibly but you may have been too generous on margins and floating rules. The default browser style should maybe respected because it can introduce false positive / negative when working in web development as a frontend developer.

Thank you if you can fix it!

**Comment by vinceliuice** [comment]
Thanks, I'll find a way to fix this.

**Comment by vinceliuice** [comment]
I adjusted a bit, you can download the last one and try again

**Comment by Artusamak** [comment]
It looks like it's fixed. Thank your for the quick fix!

**Comment by vinceliuice** [comment]
You are welcome
