### ISSUE TITLE
No radio button styling with vimix-dark

### ISSUE THREAD

**Issue by ChrisLane** [vinceliuice/vimix-gtk-themes#59]
In FireFox I have noticed that while using the vimix-dark theme, radio buttons and checkboxes occasionally do not any styling at all and so cannot be seen.

![](https://i.imgur.com/5VWtpzH.png)

**Comment by vinceliuice** [comment]
FIxed now

**Comment by ChrisLane** [comment]
Thanks, still seem to be missing styling for checked boxes too though.

**Comment by vinceliuice** [comment]
![default](https://user-images.githubusercontent.com/7604295/35714517-1778e2ca-0808-11e8-90b3-2c0d663aae58.png)
But it works well on my firefox 58,

**Comment by ChrisLane** [comment]
Firefox 58.0.1:
![](https://i.imgur.com/DkvMkvB.png)

I can confirm that Vimix-Dark-Beryl checked boxes are visible but not in Vimix-Dark.

**Comment by vinceliuice** [comment]
Sorry about this, now it's fixed

**Comment by ChrisLane** [comment]
No worries, thanks :)
