### ISSUE TITLE
Problems with GTK+ theme

### ISSUE THREAD

**Issue by henriquearthur** [vinceliuice/vimix-gtk-themes#6]
![captura de tela de 2017-01-18 14-52-33](https://cloud.githubusercontent.com/assets/5016325/22076191/d126b90a-dd8d-11e6-9cf2-9f39d803c3ec.png)

I'm facing issues with GTK+ theme as you can see on the image above. All the programs are like this (tweak tool, nautilus, transmission, etc), context menus, etc...

Gnome Shell seems to be working fine.

- Ubuntu GNOME 16.04
- Installed by `Vimix-installer.sh`
- Already installed `gtk2-engines-murrine gtk2-engines-pixbuf`
- This happens on all variants of Vimix
- Already tried to install it manually

At first, I thought that the theme is not compatible to my system, but your README says `GTK 3, GTK 2 and Gnome-Shell which supports GTK 3 and GTK 2 based desktop environments like Gnome, Unity, Budgie, Pantheon, XFCE, Mate, etc.`

**Comment by cwchien** [comment]
As far as I know, Vimix is compatible to gtk-3.20 (which is Ubuntu 16.10).

Ubuntu 16.04 use gtk-3.18, this may be the cause.

**Comment by henriquearthur** [comment]
My mistake. Thought it was compatible. Thanks!
