### ISSUE TITLE
Firefox, white text on white background in input boxes

### ISSUE THREAD

**Issue by ChrisLane** [vinceliuice/vimix-gtk-themes#60]
There is text in all of these input boxes.

![](https://i.imgur.com/QVFuisb.png)

**Comment by vinceliuice** [comment]
I adjusted the entry settings, you can try again

**Comment by ChrisLane** [comment]
Doesn't seem to have changed.

**Comment by vinceliuice** [comment]
Can you tell me the URL you visited, that'll help me test

**Comment by ChrisLane** [comment]
Maybe try the "source code" boxes on this website?
http://www.html.am/html-codes/textboxes/html-textbox.cfm

**Comment by vinceliuice** [comment]
Fixed now
