### ISSUE TITLE
Vimix-Dark: Firefox white selection highlight & text

### ISSUE THREAD

**Issue by ChrisLane** [vinceliuice/vimix-gtk-themes#61]
When highlighting text, the selection highlighting is white as well as the text, this makes it look like anything selected turns invisible on white pages with white background.

An example of where this happens is pretty much anywhere on GitHub.

**Comment by vinceliuice** [comment]
Fixed now

**Comment by vinceliuice** [comment]
Can you give me a screenshot?

**Comment by ChrisLane** [comment]
![](https://imgur.com/0w4pRG1)

**Comment by vinceliuice** [comment]
Now, it is fixed!
