### ISSUE TITLE
shell-theme with ugly background in GDM login screen. 

### ISSUE THREAD

**Issue by edward-p** [vinceliuice/vimix-gtk-themes#62]
#### Then I get the ugly background as below: (just like a black ellipse in the center) 
![gdm-screenshot](https://user-images.githubusercontent.com/7891089/35917149-fb5fb804-0c47-11e8-9882-ec36d6da556e.png)
#### After seeing [Arch Wiki - GDM#Log-in_screen_background_image](https://wiki.archlinux.org/index.php/GDM#Log-in_screen_background_image), I know that the background which GDM uses is defined in `gnome-shell.css` somewhere like the follows:
	#lockDialogGroup {
	  background: #2e3436 url(filename);
	  background-size: [WIDTH]px [HEIGHT]px;
	  background-repeat: no-repeat;
	}

#### But in your shell-theme:

![deepinscreenshot_select-area_20180207204751](https://user-images.githubusercontent.com/7891089/35917199-34681b78-0c48-11e8-9c9c-e00e2ef3ff61.png)

#### I guess that is exactly what causes this issue, but I have no ideas about how to improve.

**Comment by vinceliuice** [comment]
I'll change the background color, thanks for your feedback

**Comment by vinceliuice** [comment]
Now you can try again!
