### ISSUE TITLE
Top bar bottom border looks strange

### ISSUE THREAD

**Issue by rawsh** [vinceliuice/vimix-gtk-themes#63]
In activities overview. How can I remove it?

**Comment by vinceliuice** [comment]
What desktop you are using? gnome-shell topbar?

**Comment by rawsh** [comment]
@vinceliuice yes

**Comment by rawsh** [comment]
Please see:

![screenshot from 2018-02-12 09-31-06](https://user-images.githubusercontent.com/7035671/36104410-92e2e880-0fd7-11e8-80c5-81bdefe3ce11.png)
![screenshot from 2018-02-12 09-31-19](https://user-images.githubusercontent.com/7035671/36104411-92f9e6ac-0fd7-11e8-9350-032908da3290.png)

**Comment by vinceliuice** [comment]
I don't set any shadow or border to gnome-shell topbar (I checked my gnome-shell theme, It works well!), are you sure you are using vimix gnome-shell theme?

**Comment by rawsh** [comment]
yup

![screenshot from 2018-02-12 09-41-42](https://user-images.githubusercontent.com/7035671/36104932-f66f0a0e-0fd8-11e8-87ae-1f52df14bb08.png)

**Comment by vinceliuice** [comment]
![2018-02-12 23-44-09](https://user-images.githubusercontent.com/7604295/36105101-c16c6c72-104e-11e8-88d0-f803b335e588.png)
![2018-02-12 23-44-23](https://user-images.githubusercontent.com/7604295/36105102-c1c134be-104e-11e8-9007-4a6cd7ad084f.png)
This is how it looks on my desktop, maybe you should download the last version on github and try again! ( on older version I did set shadows to topbar on gnome-shell themes, but recently versions I removed!)

**Comment by rawsh** [comment]
@vinceliuice Huh. I'm on the latest git version

**Comment by vinceliuice** [comment]
Just download this : https://github.com/vinceliuice/vimix-gtk-themes/archive/master.zip

**Comment by vinceliuice** [comment]
![2018-02-13 10-53-09](https://user-images.githubusercontent.com/7604295/36131404-998828dc-10ac-11e8-8f3a-89453b1dfa2b.png)
I checked the code again and confirmed that no shading and borders were added
