### ISSUE TITLE
[ Feature request ] Supporting budgie

### ISSUE THREAD

**Issue by josephscade** [vinceliuice/vimix-gtk-themes#65]
Hello,
Budgie is now a very popular desktop environment as the main distro which ships it is 5th most popular distribution (according to distrowatch).
As of today, vimix looks a bit ugly on this desktop environment.
Is it possible to support this environment ?
If you need some screenshots or tests, tell me
Best regards

**Comment by vinceliuice** [comment]
Thanks! Since more and more people use this desktop, I will plan to make Vimix support Budgie

**Comment by vinceliuice** [comment]
Now! Vimix supported Budgie, you can download the last version

**Comment by josephscade** [comment]
Thank you so much, I'm very happy to use both the best theme ever and the best desktop environment ever :)

**Comment by vinceliuice** [comment]
You are welcome
