### ISSUE TITLE
Make a compact variant

### ISSUE THREAD

**Issue by spsf64** [vinceliuice/vimix-gtk-themes#68]
Can you make a more compact theme?
I mean the spacing between items are a bit big, please compare with adapta-eta in the screenshots below..
Thanks for this great theme!

Edit: these shots are from archlinux+XFCE 

*Adapta:

![adapta](https://user-images.githubusercontent.com/1877391/36731325-3009a518-1ba9-11e8-8029-447570e5ee68.png)

*Vimix:

![vimix](https://user-images.githubusercontent.com/1877391/36731349-3ddfded2-1ba9-11e8-827e-4036e6f345fb.png)

**Comment by vinceliuice** [comment]
I get it， I can adjust the gtk2 theme menuitem height

**Comment by vinceliuice** [comment]
Now fixed

**Comment by spsf64** [comment]
@vinceliuice I tried the latest git from arch and it did not work :(
The height / spacing in menu items still the same...

**Comment by vinceliuice** [comment]
I already adjustied more small size, but if still feel not enough, I can tell you how to adjust the file to get the size you want:
First open ../gtk-2.0/main.rc
Then search :  style "menu_item"  :
style "menu_item" {
  xthickness = 4
  ythickness = 2
...
Change the value of " ythickness = 2 ", set 1 or 0 ( more less means more low in height )
And then search :  style "separator_menu_item" : 
style "separator_menu_item" {
  xthickness = 0
  ythickness = 2
...
Still change the value of " ythickness = 2 ", set 1 or 0 ( more less means more low in height ) this is the height of menu item separators

**Comment by spsf64** [comment]
Still the same, apparently the vertical spacing is not changing...
I tried other settings but did not find the correct one...

**Comment by vinceliuice** [comment]
When you changed the size, you should set another theme then set back or relogin your desktop to see the changes

**Comment by spsf64** [comment]
Yes, I know, even reboot, no go...
I wiil try more and let you know, but I don't think I will find it :(
Thanks for your replies!
