### ISSUE TITLE
关于主题的展示图片。

### ISSUE THREAD

**Issue by ilovesusu** [vinceliuice/vimix-gtk-themes#7]
我非常喜欢你的这套主题，喜欢这个配色，但是我就是想问一句，你的QQ是wine的吗？！

**Comment by ilovesusu** [comment]
https://cn.pling.com/img/f/7/e/b/bd499935bebd7e7702844c32b7f59a91dd1d.jpg

**Comment by vinceliuice** [comment]
chrome的网页版而已，不是wine的，不怎么用qq所以没去搞wine的

**Comment by ilovesusu** [comment]
原来是这样阿！
