### ISSUE TITLE
What are the steps to Uninstall Vimix?

### ISSUE THREAD

**Issue by balogic** [vinceliuice/vimix-gtk-themes#70]
Please share the steps to uninstall Vimix

**Comment by vinceliuice** [comment]
You can read the README file:
...
Install Or Uninstall
Open the terminal at current directory.

Run

./Install
Or double-click to open that script files and select "run at the terminal" at nautilus.

**Comment by vinceliuice** [comment]
Now you can download the Vimix-installer to install or remove vimix
