### ISSUE TITLE
Small launcher icons in Xfce panel

### ISSUE THREAD

**Issue by MaycneSonahoz** [vinceliuice/vimix-gtk-themes#71]
Hi,

When using the Vimix themes on Xfce 4.12, the launchers icons in the panel are quite small.
![Imgur](https://i.imgur.com/hMYOrWu.jpg)

Is it on purpose? Or can you make them bigger?

Best regards, and thanks for the good work.
Maycne.

**Comment by vinceliuice** [comment]
You can read the README file:
...
Install Or Uninstall
Open the terminal at current directory.

Run

./Install
Or double-click to open that script files and select "run at the terminal" at nautilus.

**Comment by MaycneSonahoz** [comment]
I think it does. ;)
https://forum.manjaro.org/t/gtk-themes-and-panel-icon-size-on-xfce/41666

**Comment by vinceliuice** [comment]
Thanks I don't know how to deal with this before, Now I can fix

**Comment by MaycneSonahoz** [comment]
I tested the update, that's better. Thanks!

**Comment by vinceliuice** [comment]
You are welcome
