### ISSUE TITLE
Chrome address bar looks disabled

### ISSUE THREAD

**Issue by jose-sanchezm** [vinceliuice/vimix-gtk-themes#73]
Hello, in Vimix, the Chrome address bar has the same background as the toolbar and so, it looks like it's disabled.

![chrome_vimix](https://user-images.githubusercontent.com/18676221/37226390-049dfe40-23da-11e8-9336-aacfad685078.png)

For comparison, this is how it looks in the base Materia theme (and any other theme that I've tried)

![chrome_materia](https://user-images.githubusercontent.com/18676221/37226436-3b04abfa-23da-11e8-8ae9-e1749206d501.png)

In Materia it's clear that's an enabled input field while in Vimix it looks like it's a disabled input.

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed now
