### ISSUE TITLE
Colored title bar buttons not visible in Mate

### ISSUE THREAD

**Issue by enyone** [vinceliuice/vimix-gtk-themes#75]
Colored title bar buttons not visible in Mate. Only normal `_ [] x` in black and white.

MATE Desktop Environment 1.18.0

Debian 9.4

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed now

**Comment by enyone** [comment]
Works like a charm. Thanks.

**Comment by vinceliuice** [comment]
You are welcome!
