### ISSUE TITLE
Xfce menus "height" still too big

### ISSUE THREAD

**Issue by spsf64** [vinceliuice/vimix-gtk-themes#76]
Please refer to the issue already closed at:
https://github.com/vinceliuice/vimix-gtk-themes/issues/68
I tried the latest git version in achlinux and see no difference...
Thanks in advance

**Comment by spsf64** [comment]
Closing as i didn't see your response before, I'll check and report later
Sorry about this...

**Comment by vinceliuice** [comment]
That's ok! if you still get problems you can still feedback here
