### ISSUE TITLE
Checkboxes display improperly

### ISSUE THREAD

**Issue by Dexger** [vinceliuice/vimix-gtk-themes#77]
Latest version of Vimix check boxes show up like this:
![alt text](https://i.imgur.com/ZWJInPF.png)

**Comment by vinceliuice** [comment]
Just reinstall it, png and svg file missing

**Comment by Dexger** [comment]
Okay thanks I'll try that!

**Comment by Dexger** [comment]
I reinstalled and I still have weird red check boxes... :(   Am I just doing something wrong, or is there something else that could be causing it?

**Comment by Dexger** [comment]
Ok, I just ran the install script without sudo so the files went to ~/.themes and it worked. I have no idea why it wasn't working in /usr/share/themes. Anyways, thanks for the quick response! :D

**Comment by vinceliuice** [comment]
I’ll check install script maybe it have issues on root
