### ISSUE TITLE
[Feature Request] Use more darker colors for theme dark variant

### ISSUE THREAD

**Issue by ceyhunn** [vinceliuice/vimix-gtk-themes#79]
I think, dark variant color a little bit lighter than Adapta dark variant. it would be nice to use more darker colors.

**Comment by aquatix** [comment]
An amber variant on vimix-dark-laptop-ruby would be appreciated. The red is bold, and I kind of like it (and use it), but it's a bit too much in some cases.

Anyway, thanks for these great themes!

**Comment by Bruce-McL** [comment]
Your Vimix dark gray and red themes have a lighter background than the Vimix dark blue and green themes. The backgrounds for gray and red look good. The backgrounds on the blue and green themes look too light for me. I am using your themes in Solus Budgie.
