### ISSUE TITLE
Could you make a more compact version of the themes?

### ISSUE THREAD

**Issue by Ufeldraku** [vinceliuice/vimix-gtk-themes#8]
I write this because I really love your theme, but thanks to Gnome 3, Things are too big, so, a more compact version of your themes would be really nice.
In 1366x768 look at this
http://imgur.com/gallery/NswAV
[Please read the text I wrote there.]

Thanks!

**Comment by cwchien** [comment]
Have you tried the "Dark-Laptop" version?
Those named with "Laptop" are more compact ones.

**Comment by Ufeldraku** [comment]
Yeah, of course! but it's not compact enough.

**Comment by Ufeldraku** [comment]
http://imgur.com/gallery/iwsMs
In Xorg it seems that's smaller, but it has a black bar.
