### ISSUE TITLE
scrollbar is too fat

### ISSUE THREAD

**Issue by phocean** [vinceliuice/vimix-gtk-themes#84]
Hi,

Awesome work, simply almost perfect.

Sadly, what stopped me using it is the fat scrollbar. It is too big, the one in Arc, for instance, is much better.

**Comment by vinceliuice** [comment]
Now you can try the last version, I make the size smaller

**Comment by phocean** [comment]
Perfect ! Thank you !

**Comment by vinceliuice** [comment]
You are welcome!
