### ISSUE TITLE
[Feature Request] Custom Accent Colours

### ISSUE THREAD

**Issue by Mibo5354** [vinceliuice/vimix-gtk-themes#87]
Is there away to be able to pick the accent colour? Unfortunately the standard `gtk-theme-config` doesn't change anything in this theme. I assume because this theme is very complex.

**Comment by vinceliuice** [comment]
You can edit the _colors.scss to change the color and then run parse-sass.sh rebuild this theme

**Comment by vinceliuice** [comment]
Yes. no quick way
