### ISSUE TITLE
Need Wallpaper

### ISSUE THREAD

**Issue by V3rB0se** [vinceliuice/vimix-gtk-themes#88]
lora

**Comment by Micro-Biology** [comment]
https://github.com/vinceliuice/vimix-gtk-themes/tree/images only 720p though

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/vimix-kde/tree/master/wallpaper

**Comment by V3rB0se** [comment]
thanks lol its been 4 years hope you're doing good 

> https://github.com/vinceliuice/vimix-kde/tree/master/wallpaper
