### ISSUE TITLE
Not working window buttons in calculator.

### ISSUE THREAD

**Issue by sant123** [vinceliuice/vimix-gtk-themes#89]
Hi and thanks for this awesome theme!!! However, I don't know what I'm doing wrong but my calculator doesn't apply Apple Window Buttons. 

![image](https://user-images.githubusercontent.com/7959437/41868234-1296390e-787b-11e8-9623-229492382144.png)

**Comment by vinceliuice** [comment]
Because this calculator is snap app, you can remove it and install default gnome version

**Comment by sant123** [comment]
Ohhhh it's that. Thank you!
