### ISSUE TITLE
Font colour in window title bar incorrect in Light themes on Unity

### ISSUE THREAD

**Issue by happydemic** [vinceliuice/vimix-gtk-themes#9]
Hi,

Ubuntu 16.10 / gtk 3.20, Unity, Vimix from NoobsLab package.

I have switched to your theme from Flatabulous, and I love vimix!

Quick note: in Unity, in the Vimix-light themes. text in the window title bar appears almost white, and is hard to read against the pale window title bar background

![screenshot from 2017-01-23 23-11-00](https://cloud.githubusercontent.com/assets/12738878/22227081/431b44a4-e1c1-11e6-89b5-b0133822c706.png)

Thanks for the great theme!

**Comment by vinceliuice** [comment]
You can try log out and log in，this is not the bug of my theme but the problem of the unity，the color of the font on windows decoration can display correct only after you log out.

**Comment by happydemic** [comment]
The font colour in the window decoration is unchanged for me by log out & log in (or reboot). 

Other gtk styles change the window decoration font colour instantly on my system, e.g. Flat-plat-light, Vertex-light. Flatabulous. No log out is required.

**Comment by vinceliuice** [comment]
Maybe there is something wrong with the theme, thanks any way, I'll check this and find out this bug.

**Comment by vinceliuice** [comment]
It's fixed now

**Comment by happydemic** [comment]
颜色是完美的。谢谢！

**Comment by vinceliuice** [comment]
中国同胞啊！不客气！
