### ISSUE TITLE
Gnome 3.30 support

### ISSUE THREAD

**Issue by Ufeldraku** [vinceliuice/vimix-gtk-themes#98]
The theme works normally on Gnome 3.30 but the bars on the system menu, in the top bar, where the battery. wifi, and sound are, use the adwaita theme.

**Comment by vinceliuice** [comment]
That need gnome-shell themes, you should use gnome-tweaks to turn "User themes" on and then set shell themes

![2018-09-18 08-21-06](https://user-images.githubusercontent.com/7604295/45657348-9484a700-bb1c-11e8-9ecc-fb01125dfb65.png)

**Comment by alraban** [comment]
I can confirm the reported issue on Gnome 3.30 even with the user themes shell extension enabled.  

Even with user themes enabled, the vimix shell themes no longer change the colors of the slider bars in the upper right hand corner menus, although the "grab handle" dot does change color correctly to follow the vimix theme, which suggests that things are only partially broken by the change.

**Comment by vinceliuice** [comment]
I update to gnome 3.30 and find this issue too, but this seems hard to be fixed, all gnome-shell themes have this issue

**Comment by vinceliuice** [comment]
This issue fixed now!
