### ISSUE TITLE
Libreoffice white on white

### ISSUE THREAD

**Issue by matteoarrighi** [vinceliuice/vimix-gtk-themes#99]
When using Libreoffice (I guess it happens with other programs as well), the background of selected items is white (with white text). This happens only with Vimix-Dark and Vimix-Dark-Laptop.
Screenshot below.
Vimix-Dark-Laptop-Beryl 
![bug 1](https://user-images.githubusercontent.com/36959661/45906632-25959f80-bdf5-11e8-86e5-9a8f299945d5.png)
![bug 3](https://user-images.githubusercontent.com/36959661/45906659-4231d780-bdf5-11e8-88c4-b4502ca153f9.png)

Vimix-Dark-Laptop
![bug 2](https://user-images.githubusercontent.com/36959661/45906654-3c3bf680-bdf5-11e8-8872-429e1be3eb09.png)
![bug 4](https://user-images.githubusercontent.com/36959661/45906664-465df500-bdf5-11e8-8d99-adabd7e88ea7.png)

**Comment by vinceliuice** [comment]
It fixed now
